//! Sprite loading. All art comes from `assets/sprites/`, generated by
//! `tools/gen_sprites.py` — regenerate there, never edit PNGs.

use anyhow::{Context, Result};
use macroquad::audio::{Sound, load_sound};
use macroquad::prelude::{FilterMode, Texture2D, load_texture};
use oxide_sim::{Faction, UnitKind};

/// Every texture the shell draws.
pub struct Sprites {
    /// Ground variants, picked per tile by position hash.
    pub ground: [Texture2D; 3],
    /// Rock overlay.
    pub rock: Texture2D,
    /// Scrap node at >2/3 remaining.
    pub scrap_full: Texture2D,
    /// Scrap node at 1/3–2/3.
    pub scrap_mid: Texture2D,
    /// Scrap node below 1/3.
    pub scrap_low: Texture2D,
    foundry: [Texture2D; 2],
    harvester: [Texture2D; 2],
    sentinel: [Texture2D; 2],
}

async fn tex(name: &str) -> Result<Texture2D> {
    let path = format!("assets/sprites/{name}.png");
    let texture = load_texture(&path)
        .await
        .with_context(|| format!("loading {path} (run from the workspace root)"))?;
    texture.set_filter(FilterMode::Linear);
    Ok(texture)
}

fn faction_index(faction: Faction) -> usize {
    match faction {
        Faction::Ferrous => 0,
        Faction::Cupric => 1,
    }
}

impl Sprites {
    /// Loads everything up front; missing files are a startup error, not a
    /// mid-game pop.
    pub async fn load() -> Result<Self> {
        Ok(Self {
            ground: [
                tex("ground_0").await?,
                tex("ground_1").await?,
                tex("ground_2").await?,
            ],
            rock: tex("rock").await?,
            scrap_full: tex("scrap_full").await?,
            scrap_mid: tex("scrap_mid").await?,
            scrap_low: tex("scrap_low").await?,
            foundry: [tex("foundry_ferrous").await?, tex("foundry_cupric").await?],
            harvester: [
                tex("harvester_ferrous").await?,
                tex("harvester_cupric").await?,
            ],
            sentinel: [
                tex("sentinel_ferrous").await?,
                tex("sentinel_cupric").await?,
            ],
        })
    }

    /// The building sprite for a faction.
    pub fn foundry(&self, faction: Faction) -> &Texture2D {
        &self.foundry[faction_index(faction)]
    }

    /// The unit sprite for a kind and faction.
    pub fn unit(&self, kind: UnitKind, faction: Faction) -> &Texture2D {
        match kind {
            UnitKind::Harvester => &self.harvester[faction_index(faction)],
            UnitKind::Sentinel => &self.sentinel[faction_index(faction)],
        }
    }
}

/// Every clip the shell plays. Generated by `tools/gen_sounds.py`.
pub struct Sounds {
    /// An attack landing.
    pub laser: Sound,
    /// A unit popping.
    pub unit_death: Sound,
    /// A building coming down.
    pub building_boom: Sound,
    /// Your harvester delivering.
    pub deposit: Sound,
    /// Your Foundry finishing a unit.
    pub train_done: Sound,
    /// Menu activation.
    pub click: Sound,
    /// You won.
    pub victory: Sound,
    /// You didn't.
    pub defeat: Sound,
}

async fn clip(name: &str) -> Result<Sound> {
    let path = format!("assets/sounds/{name}.wav");
    load_sound(&path)
        .await
        .with_context(|| format!("loading {path} (run from the workspace root)"))
}

impl Sounds {
    /// Loads every clip up front, like [`Sprites::load`].
    pub async fn load() -> Result<Self> {
        Ok(Self {
            laser: clip("laser").await?,
            unit_death: clip("unit_death").await?,
            building_boom: clip("building_boom").await?,
            deposit: clip("deposit").await?,
            train_done: clip("train_done").await?,
            click: clip("click").await?,
            victory: clip("victory").await?,
            defeat: clip("defeat").await?,
        })
    }
}
