//! Sprite loading. All art comes from `assets/sprites/`, generated by
//! `tools/gen_sprites.py` — regenerate there, never edit PNGs.

use anyhow::{Context, Result};
use macroquad::audio::{Sound, load_sound};
use macroquad::prelude::{FilterMode, Rect, Texture2D, load_texture};
use oxide_sim::{BuildingKind, Faction, UnitKind};

/// Every sprite the shell draws, as regions of ONE texture.
///
/// A single atlas means macroquad batches the entire world into a handful
/// of draw calls; the previous texture-per-sprite scheme flushed the batch
/// on nearly every tile and halved the framerate zoomed out.
pub struct Sprites {
    texture: Texture2D,
    /// Verb pictograms for cards and order chips, indexed by
    /// [`crate::panel::VerbIcon`].
    verb_icons: [Rect; 12],
    ground: [Rect; 6],
    rock: [Rect; 4],
    /// Full-tile exclusion barriers, indexed `neighbor_mask * 2 + variant`.
    peak_barriers: [Rect; 32],
    turret_barrel: [Rect; 3],
    flak_mount: [Rect; 3],
    bastion_mount: [Rect; 3],
    rock_skirt: Rect,
    decals: [Rect; 4],
    /// Six flat ground-dressing variants for each shipped theme.
    theme_props: [Rect; 36],
    scrap_full: Rect,
    scrap_mid: Rect,
    scrap_low: Rect,
    scrap_rich: Rect,
    muzzle_flash: Rect,
    scorch: Rect,
    wreck_pile: Rect,
    air_shadow: Rect,
    burst: Rect,
    foundry: [Rect; 3],
    turret: [Rect; 3],
    fabricator: [Rect; 3],
    flak_turret: [Rect; 3],
    bastion: [Rect; 3],
    array: [Rect; 3],
    reclaimer: [Rect; 3],
    repair_bay: [Rect; 3],
    foundry_work: [[Rect; 3]; 3],
    fabricator_work: [[Rect; 3]; 3],
    array_work: [[Rect; 3]; 3],
    reclaimer_work: [[Rect; 3]; 3],
    repair_bay_work: [[Rect; 3]; 3],
    construction: [[Rect; 3]; SITE_FRAME_COUNT * BUILDING_KIND_COUNT],
    harvester: [Rect; 3],
    harvester_scoop: [[Rect; 3]; 2],
    harvester_tread: [[Rect; 3]; 2],
    scaffold: [Rect; 2],
    debris: [Rect; 3],
    scuttler: [Rect; 3],
    scuttler_move: [[Rect; 3]; 2],
    lancer: [Rect; 3],
    lancer_move: [[Rect; 3]; 2],
    sentinel: [Rect; 3],
    sentinel_move: [[Rect; 3]; 2],
    bombard: [Rect; 3],
    bombard_move: [[Rect; 3]; 2],
    flakhound: [Rect; 3],
    flakhound_tread: [[Rect; 3]; 2],
    stinger: [Rect; 3],
    stinger_move: [[Rect; 3]; 2],
    buzzard: [Rect; 3],
    darter: [Rect; 3],
    talon: [Rect; 3],
    wisp: [Rect; 3],
}

fn faction_index(faction: Faction) -> usize {
    match faction {
        Faction::Ferrous => 0,
        Faction::Cupric => 1,
    }
}

/// Third slot of every faction-varied sprite row: the allegiance-accent
/// mask (the pixels where the two faction variants differ, grayscale).
const ACCENT: usize = 2;

/// The atlas manifest as `tools/gen_sprites.py` writes it.
type Manifest = std::collections::HashMap<String, [f32; 4]>;

/// Sprites with no faction variants: one region, one name.
const SINGLE_KEYS: [&str; 10] = [
    "rock_skirt",
    "scrap_full",
    "scrap_mid",
    "scrap_low",
    "scrap_rich",
    "muzzle_flash",
    "scorch",
    "wreck_pile",
    "air_shadow",
    "burst",
];

/// Verb pictograms, ordered to match [`crate::panel::VerbIcon`].
const VERB_ICON_KEYS: [&str; 12] = [
    "icon_stop",
    "icon_move",
    "icon_attack_move",
    "icon_attack",
    "icon_patrol",
    "icon_harvest",
    "icon_build",
    "icon_repair",
    "icon_salvage",
    "icon_cancel",
    "icon_rally",
    "icon_idle",
];

const GROUND_KEYS: [&str; 6] = [
    "ground_0", "ground_1", "ground_2", "ground_3", "ground_4", "ground_5",
];

const ROCK_KEYS: [&str; 4] = ["rock_0", "rock_1", "rock_2", "rock_3"];

/// Full-tile barriers, ordered `neighbor_mask * 2 + variant`. The mask is
/// north/east/south/west in bits 0 through 3.
const PEAK_BARRIER_KEYS: [&str; 32] = [
    "peak_barrier_00_0",
    "peak_barrier_00_1",
    "peak_barrier_01_0",
    "peak_barrier_01_1",
    "peak_barrier_02_0",
    "peak_barrier_02_1",
    "peak_barrier_03_0",
    "peak_barrier_03_1",
    "peak_barrier_04_0",
    "peak_barrier_04_1",
    "peak_barrier_05_0",
    "peak_barrier_05_1",
    "peak_barrier_06_0",
    "peak_barrier_06_1",
    "peak_barrier_07_0",
    "peak_barrier_07_1",
    "peak_barrier_08_0",
    "peak_barrier_08_1",
    "peak_barrier_09_0",
    "peak_barrier_09_1",
    "peak_barrier_0a_0",
    "peak_barrier_0a_1",
    "peak_barrier_0b_0",
    "peak_barrier_0b_1",
    "peak_barrier_0c_0",
    "peak_barrier_0c_1",
    "peak_barrier_0d_0",
    "peak_barrier_0d_1",
    "peak_barrier_0e_0",
    "peak_barrier_0e_1",
    "peak_barrier_0f_0",
    "peak_barrier_0f_1",
];

const DECAL_KEYS: [&str; 4] = ["decal_crack", "decal_plate", "decal_stain", "decal_wreck"];

/// Six flat ground-dressing sprites per shipped theme. Theme order is
/// mirrored by [`Sprites::theme_prop`].
const THEME_PROP_KEYS: [&str; 36] = [
    "theme_rusted_yard_0",
    "theme_rusted_yard_1",
    "theme_rusted_yard_2",
    "theme_rusted_yard_3",
    "theme_rusted_yard_4",
    "theme_rusted_yard_5",
    "theme_cold_circuitry_0",
    "theme_cold_circuitry_1",
    "theme_cold_circuitry_2",
    "theme_cold_circuitry_3",
    "theme_cold_circuitry_4",
    "theme_cold_circuitry_5",
    "theme_quarry_dust_0",
    "theme_quarry_dust_1",
    "theme_quarry_dust_2",
    "theme_quarry_dust_3",
    "theme_quarry_dust_4",
    "theme_quarry_dust_5",
    "theme_basalt_0",
    "theme_basalt_1",
    "theme_basalt_2",
    "theme_basalt_3",
    "theme_basalt_4",
    "theme_basalt_5",
    "theme_slag_0",
    "theme_slag_1",
    "theme_slag_2",
    "theme_slag_3",
    "theme_slag_4",
    "theme_slag_5",
    "theme_verdigris_0",
    "theme_verdigris_1",
    "theme_verdigris_2",
    "theme_verdigris_3",
    "theme_verdigris_4",
    "theme_verdigris_5",
];

fn theme_prop_row(theme: &str) -> Option<usize> {
    match theme {
        "rusted-yard" => Some(0),
        "cold-circuitry" => Some(1),
        "quarry-dust" => Some(2),
        "basalt" => Some(3),
        "slag" => Some(4),
        "verdigris" => Some(5),
        _ => None,
    }
}

const SCAFFOLD_KEYS: [&str; 2] = ["scaffold_dense", "scaffold_sparse"];

const DEBRIS_KEYS: [&str; 3] = ["debris_0", "debris_1", "debris_2"];

/// The Turret's gun is faction-varied like a unit, but belongs to no kind.
const TURRET_BARREL_STEM: &str = "turret_barrel";
const FLAK_MOUNT_STEM: &str = "flak_mount";
const BASTION_MOUNT_STEM: &str = "bastion_mount";

/// The Harvester's dig frames hang off its own stem.
const SCOOP_SUFFIXES: [&str; 2] = ["_scoop1", "_scoop2"];
const TREAD_SUFFIXES: [&str; 2] = ["_tread1", "_tread2"];
const MOVE_SUFFIXES: [&str; 2] = ["_move1", "_move2"];
const WORK_SUFFIXES: [&str; 3] = ["_work1", "_work2", "_work3"];
const SITE_STAGES: usize = 3;
const SITE_PHASES: usize = 2;
const SITE_FRAME_COUNT: usize = SITE_STAGES * SITE_PHASES;
const BUILDING_KIND_COUNT: usize = 8;

/// The atlas stem a unit kind's rows live under.
fn unit_stem(kind: UnitKind) -> &'static str {
    kind.name()
}

/// The atlas stem a building kind's rows live under. Exhaustive on
/// purpose: a new kind must say where its art is before it compiles.
fn building_stem(kind: BuildingKind) -> &'static str {
    match kind {
        BuildingKind::Foundry => "foundry",
        BuildingKind::Turret => "turret",
        BuildingKind::Fabricator => "fabricator",
        BuildingKind::FlakTurret => "flak_turret",
        BuildingKind::Bastion => "bastion",
        BuildingKind::Array => "array",
        BuildingKind::Reclaimer => "reclaimer",
        BuildingKind::RepairBay => "repair_bay",
    }
}

fn building_index(kind: BuildingKind) -> usize {
    match kind {
        BuildingKind::Foundry => 0,
        BuildingKind::Turret => 1,
        BuildingKind::Fabricator => 2,
        BuildingKind::FlakTurret => 3,
        BuildingKind::Bastion => 4,
        BuildingKind::Array => 5,
        BuildingKind::Reclaimer => 6,
        BuildingKind::RepairBay => 7,
    }
}

/// The three names every faction-varied row carries.
fn variant_keys(stem: &str, suffix: &str) -> [String; 3] {
    [
        format!("{stem}_ferrous{suffix}"),
        format!("{stem}_cupric{suffix}"),
        format!("{stem}_accent{suffix}"),
    ]
}

fn lookup(rects: &Manifest, name: &str) -> Result<Rect> {
    let [x, y, w, h] = rects
        .get(name)
        .copied()
        .with_context(|| format!("sprite {name:?} missing from atlas"))?;
    Ok(Rect::new(x, y, w, h))
}

fn pick<const N: usize>(rects: &Manifest, keys: [&str; N]) -> Result<[Rect; N]> {
    let mut out = [Rect::new(0.0, 0.0, 0.0, 0.0); N];
    for (slot, key) in out.iter_mut().zip(keys) {
        *slot = lookup(rects, key)?;
    }
    Ok(out)
}

fn variant_row(rects: &Manifest, stem: &str, suffix: &str) -> Result<[Rect; 3]> {
    let mut out = [Rect::new(0.0, 0.0, 0.0, 0.0); 3];
    for (slot, key) in out.iter_mut().zip(variant_keys(stem, suffix)) {
        *slot = lookup(rects, &key)?;
    }
    Ok(out)
}

fn variant_rows<const N: usize>(
    rects: &Manifest,
    stem: &str,
    suffixes: [&str; N],
) -> Result<[[Rect; 3]; N]> {
    let empty = [Rect::new(0.0, 0.0, 0.0, 0.0); 3];
    let mut out = [empty; N];
    for (row, suffix) in out.iter_mut().zip(suffixes) {
        *row = variant_row(rects, stem, suffix)?;
    }
    Ok(out)
}

/// Every kind the shell must find art for.
#[cfg(test)]
const ALL_UNIT_KINDS: [UnitKind; 11] = [
    UnitKind::Harvester,
    UnitKind::Sentinel,
    UnitKind::Scuttler,
    UnitKind::Lancer,
    UnitKind::Bombard,
    UnitKind::Flakhound,
    UnitKind::Stinger,
    UnitKind::Buzzard,
    UnitKind::Darter,
    UnitKind::Talon,
    UnitKind::Wisp,
];

const ALL_BUILDING_KINDS: [BuildingKind; 8] = [
    BuildingKind::Foundry,
    BuildingKind::Turret,
    BuildingKind::Fabricator,
    BuildingKind::FlakTurret,
    BuildingKind::Bastion,
    BuildingKind::Array,
    BuildingKind::Reclaimer,
    BuildingKind::RepairBay,
];

#[cfg(test)]
const WORK_BUILDING_KINDS: [BuildingKind; 5] = [
    BuildingKind::Foundry,
    BuildingKind::Fabricator,
    BuildingKind::Array,
    BuildingKind::Reclaimer,
    BuildingKind::RepairBay,
];

fn construction_rows(
    rects: &Manifest,
) -> Result<[[Rect; 3]; SITE_FRAME_COUNT * BUILDING_KIND_COUNT]> {
    let empty = [Rect::new(0.0, 0.0, 0.0, 0.0); 3];
    let mut out = [empty; SITE_FRAME_COUNT * BUILDING_KIND_COUNT];
    for kind in ALL_BUILDING_KINDS {
        for stage in 0..SITE_STAGES {
            for phase in 0..SITE_PHASES {
                let frame = stage * SITE_PHASES + phase;
                let suffix = format!("_site{stage}_{phase}");
                out[building_index(kind) * SITE_FRAME_COUNT + frame] =
                    variant_row(rects, building_stem(kind), &suffix)?;
            }
        }
    }
    Ok(out)
}

/// Every atlas key [`Sprites::load`] resolves, built from the same lists
/// and stems the loader itself uses.
#[cfg(test)]
fn atlas_keys() -> Vec<String> {
    let mut keys: Vec<String> = SINGLE_KEYS
        .iter()
        .chain(VERB_ICON_KEYS.iter())
        .chain(GROUND_KEYS.iter())
        .chain(ROCK_KEYS.iter())
        .chain(PEAK_BARRIER_KEYS.iter())
        .chain(DECAL_KEYS.iter())
        .chain(THEME_PROP_KEYS.iter())
        .chain(SCAFFOLD_KEYS.iter())
        .chain(DEBRIS_KEYS.iter())
        .map(|key| (*key).to_string())
        .collect();
    keys.extend(variant_keys(TURRET_BARREL_STEM, ""));
    keys.extend(variant_keys(FLAK_MOUNT_STEM, ""));
    keys.extend(variant_keys(BASTION_MOUNT_STEM, ""));
    for kind in ALL_BUILDING_KINDS {
        keys.extend(variant_keys(building_stem(kind), ""));
    }
    for kind in ALL_UNIT_KINDS {
        keys.extend(variant_keys(unit_stem(kind), ""));
    }
    for suffix in SCOOP_SUFFIXES {
        keys.extend(variant_keys(unit_stem(UnitKind::Harvester), suffix));
    }
    for kind in [UnitKind::Harvester, UnitKind::Flakhound] {
        for suffix in TREAD_SUFFIXES {
            keys.extend(variant_keys(unit_stem(kind), suffix));
        }
    }
    for kind in [
        UnitKind::Sentinel,
        UnitKind::Scuttler,
        UnitKind::Lancer,
        UnitKind::Bombard,
        UnitKind::Stinger,
    ] {
        for suffix in MOVE_SUFFIXES {
            keys.extend(variant_keys(unit_stem(kind), suffix));
        }
    }
    for kind in WORK_BUILDING_KINDS {
        for suffix in WORK_SUFFIXES {
            keys.extend(variant_keys(building_stem(kind), suffix));
        }
    }
    for kind in ALL_BUILDING_KINDS {
        for stage in 0..SITE_STAGES {
            for phase in 0..SITE_PHASES {
                keys.extend(variant_keys(
                    building_stem(kind),
                    &format!("_site{stage}_{phase}"),
                ));
            }
        }
    }
    keys
}

/// Where game data lives. A macOS .app bundle keeps it in
/// Contents/Resources beside `Contents/MacOS/<exe>`; development runs
/// from the workspace root. Resolved once by probing for the atlas —
/// the one file no build ships without.
pub fn resource_root() -> std::path::PathBuf {
    // Native automation runs from an isolated writable directory so
    // local replays and screenshots cannot perturb a golden walk. It
    // points back at the read-only workspace resources explicitly.
    if let Some(root) = std::env::var_os("OXIDE_RESOURCE_ROOT") {
        return root.into();
    }
    if let Ok(exe) = std::env::current_exe()
        && let Some(dir) = exe.parent()
    {
        let bundled = dir.join("../Resources");
        if bundled.join("assets/sprites/atlas.png").exists() {
            return bundled;
        }
    }
    std::path::PathBuf::from(".")
}

/// A resource path as a string macroquad's loaders accept.
pub fn resource(rel: &str) -> String {
    resource_root().join(rel).to_string_lossy().into_owned()
}

impl Sprites {
    /// Loads the atlas up front; a missing or incomplete atlas is a
    /// startup error, not a mid-game pop.
    pub async fn load() -> Result<Self> {
        let texture = load_texture(&resource("assets/sprites/atlas.png"))
            .await
            .context("loading assets/sprites/atlas.png (run from the workspace root)")?;
        texture.set_filter(FilterMode::Linear);
        let manifest = macroquad::file::load_string(&resource("assets/sprites/atlas.json"))
            .await
            .context("loading assets/sprites/atlas.json")?;
        let rects: Manifest = serde_json::from_str(&manifest).context("parsing atlas manifest")?;
        let [
            rock_skirt,
            scrap_full,
            scrap_mid,
            scrap_low,
            scrap_rich,
            muzzle_flash,
            scorch,
            wreck_pile,
            air_shadow,
            burst,
        ] = pick(&rects, SINGLE_KEYS)?;
        let unit = |kind| variant_row(&rects, unit_stem(kind), "");
        let building = |kind| variant_row(&rects, building_stem(kind), "");
        Ok(Self {
            texture,
            verb_icons: pick(&rects, VERB_ICON_KEYS)?,
            ground: pick(&rects, GROUND_KEYS)?,
            rock: pick(&rects, ROCK_KEYS)?,
            peak_barriers: pick(&rects, PEAK_BARRIER_KEYS)?,
            turret_barrel: variant_row(&rects, TURRET_BARREL_STEM, "")?,
            flak_mount: variant_row(&rects, FLAK_MOUNT_STEM, "")?,
            bastion_mount: variant_row(&rects, BASTION_MOUNT_STEM, "")?,
            rock_skirt,
            decals: pick(&rects, DECAL_KEYS)?,
            theme_props: pick(&rects, THEME_PROP_KEYS)?,
            scrap_full,
            scrap_mid,
            scrap_low,
            scrap_rich,
            muzzle_flash,
            scorch,
            wreck_pile,
            air_shadow,
            burst,
            foundry: building(BuildingKind::Foundry)?,
            turret: building(BuildingKind::Turret)?,
            fabricator: building(BuildingKind::Fabricator)?,
            flak_turret: building(BuildingKind::FlakTurret)?,
            bastion: building(BuildingKind::Bastion)?,
            array: building(BuildingKind::Array)?,
            reclaimer: building(BuildingKind::Reclaimer)?,
            repair_bay: building(BuildingKind::RepairBay)?,
            foundry_work: variant_rows(&rects, "foundry", WORK_SUFFIXES)?,
            fabricator_work: variant_rows(&rects, "fabricator", WORK_SUFFIXES)?,
            array_work: variant_rows(&rects, "array", WORK_SUFFIXES)?,
            reclaimer_work: variant_rows(&rects, "reclaimer", WORK_SUFFIXES)?,
            repair_bay_work: variant_rows(&rects, "repair_bay", WORK_SUFFIXES)?,
            construction: construction_rows(&rects)?,
            harvester: unit(UnitKind::Harvester)?,
            harvester_scoop: variant_rows(&rects, unit_stem(UnitKind::Harvester), SCOOP_SUFFIXES)?,
            harvester_tread: variant_rows(&rects, unit_stem(UnitKind::Harvester), TREAD_SUFFIXES)?,
            scaffold: pick(&rects, SCAFFOLD_KEYS)?,
            debris: pick(&rects, DEBRIS_KEYS)?,
            scuttler: unit(UnitKind::Scuttler)?,
            scuttler_move: variant_rows(&rects, unit_stem(UnitKind::Scuttler), MOVE_SUFFIXES)?,
            lancer: unit(UnitKind::Lancer)?,
            lancer_move: variant_rows(&rects, unit_stem(UnitKind::Lancer), MOVE_SUFFIXES)?,
            sentinel: unit(UnitKind::Sentinel)?,
            sentinel_move: variant_rows(&rects, unit_stem(UnitKind::Sentinel), MOVE_SUFFIXES)?,
            bombard: unit(UnitKind::Bombard)?,
            bombard_move: variant_rows(&rects, unit_stem(UnitKind::Bombard), MOVE_SUFFIXES)?,
            flakhound: unit(UnitKind::Flakhound)?,
            flakhound_tread: variant_rows(&rects, unit_stem(UnitKind::Flakhound), TREAD_SUFFIXES)?,
            stinger: unit(UnitKind::Stinger)?,
            stinger_move: variant_rows(&rects, unit_stem(UnitKind::Stinger), MOVE_SUFFIXES)?,
            buzzard: unit(UnitKind::Buzzard)?,
            darter: unit(UnitKind::Darter)?,
            talon: unit(UnitKind::Talon)?,
            wisp: unit(UnitKind::Wisp)?,
        })
    }

    /// The one texture every sprite lives in.
    pub fn texture(&self) -> &Texture2D {
        &self.texture
    }

    /// A verb pictogram's atlas region.
    pub fn verb_icon(&self, icon: crate::panel::VerbIcon) -> Rect {
        self.verb_icons[icon as usize]
    }

    /// A ground variant's atlas region.
    pub fn ground(&self, variant: usize) -> Rect {
        self.ground[variant % self.ground.len()]
    }

    /// A rock variant's atlas region.
    pub fn rock(&self, variant: usize) -> Rect {
        self.rock[variant % self.rock.len()]
    }

    /// A defense's directional mount, if its base art ships bare.
    pub fn defense_mount(&self, kind: BuildingKind, faction: oxide_sim::Faction) -> Option<Rect> {
        let row = match kind {
            BuildingKind::Turret => &self.turret_barrel,
            BuildingKind::FlakTurret => &self.flak_mount,
            BuildingKind::Bastion => &self.bastion_mount,
            _ => return None,
        };
        Some(row[faction_index(faction)])
    }

    /// The allegiance-accent mask matched to [`Self::defense_mount`].
    pub fn defense_mount_accent(&self, kind: BuildingKind) -> Option<Rect> {
        let row = match kind {
            BuildingKind::Turret => &self.turret_barrel,
            BuildingKind::FlakTurret => &self.flak_mount,
            BuildingKind::Bastion => &self.bastion_mount,
            _ => return None,
        };
        Some(row[ACCENT])
    }

    /// A full-tile exclusion barrier connected to its peak neighbors.
    pub fn peak_barrier(&self, neighbor_mask: u8, variant: usize) -> Rect {
        self.peak_barriers[usize::from(neighbor_mask & 0x0f) * 2 + variant % 2]
    }

    /// The soft shadow a rock casts on a neighboring ground tile
    /// (authored falling from the top edge; rotate toward the rock).
    pub fn rock_skirt(&self) -> Rect {
        self.rock_skirt
    }

    /// A ground decal's atlas region.
    pub fn decal(&self, variant: usize) -> Rect {
        self.decals[variant % self.decals.len()]
    }

    /// A flat ground-dressing sprite for a shipped map theme.
    pub fn theme_prop(&self, theme: &str, variant: usize) -> Option<Rect> {
        let row = theme_prop_row(theme)?;
        Some(self.theme_props[row * 6 + variant % 6])
    }

    /// The scrap sprite region for a remaining amount: anything above a
    /// standard node renders as the rich pile, then thirds of standard.
    pub fn scrap(&self, amount: u32, standard_amount: u32) -> Rect {
        if amount > standard_amount {
            self.scrap_rich
        } else if amount * 3 > standard_amount * 2 {
            self.scrap_full
        } else if amount * 3 > standard_amount {
            self.scrap_mid
        } else {
            self.scrap_low
        }
    }

    /// The muzzle-flash atlas region.
    pub fn muzzle_flash(&self) -> Rect {
        self.muzzle_flash
    }

    /// The building-death scorch decal region.
    pub fn scorch(&self) -> Rect {
        self.scorch
    }

    /// A wreck salvage pile on open ground.
    pub fn wreck_pile(&self) -> Rect {
        self.wreck_pile
    }

    /// The soft shadow a flyer casts on the ground.
    pub fn air_shadow(&self) -> Rect {
        self.air_shadow
    }

    /// The splash-detonation frame.
    pub fn burst(&self) -> Rect {
        self.burst
    }

    /// The building sprite region for a kind and faction.
    fn building_row(&self, kind: oxide_sim::BuildingKind) -> &[Rect; 3] {
        match kind {
            oxide_sim::BuildingKind::Foundry => &self.foundry,
            oxide_sim::BuildingKind::Turret => &self.turret,
            oxide_sim::BuildingKind::Fabricator => &self.fabricator,
            oxide_sim::BuildingKind::FlakTurret => &self.flak_turret,
            oxide_sim::BuildingKind::Bastion => &self.bastion,
            oxide_sim::BuildingKind::Array => &self.array,
            oxide_sim::BuildingKind::Reclaimer => &self.reclaimer,
            oxide_sim::BuildingKind::RepairBay => &self.repair_bay,
        }
    }

    pub fn building(&self, kind: oxide_sim::BuildingKind, faction: Faction) -> Rect {
        self.building_row(kind)[faction_index(faction)]
    }

    /// The allegiance-accent mask over a building's faction-colored
    /// regions — grayscale in the atlas, tinted at draw time.
    pub fn building_accent(&self, kind: oxide_sim::BuildingKind) -> Rect {
        self.building_row(kind)[ACCENT]
    }

    fn building_work_row(&self, kind: BuildingKind, frame: usize) -> Option<&[Rect; 3]> {
        let rows = match kind {
            BuildingKind::Foundry => &self.foundry_work,
            BuildingKind::Fabricator => &self.fabricator_work,
            BuildingKind::Array => &self.array_work,
            BuildingKind::Reclaimer => &self.reclaimer_work,
            BuildingKind::RepairBay => &self.repair_bay_work,
            _ => return None,
        };
        frame.checked_sub(1).and_then(|index| rows.get(index))
    }

    /// A complete authored activity frame for a working building. Frame 0
    /// is the ordinary base art and is also the reduced-motion pose.
    pub fn building_working(&self, kind: BuildingKind, faction: Faction, frame: usize) -> Rect {
        self.building_work_row(kind, frame)
            .unwrap_or_else(|| self.building_row(kind))[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::building_working`].
    pub fn building_working_accent(&self, kind: BuildingKind, frame: usize) -> Rect {
        self.building_work_row(kind, frame)
            .unwrap_or_else(|| self.building_row(kind))[ACCENT]
    }

    fn construction_row(&self, kind: BuildingKind, stage: usize, phase: usize) -> &[Rect; 3] {
        let stage = stage.min(SITE_STAGES - 1);
        let phase = phase.min(SITE_PHASES - 1);
        &self.construction[building_index(kind) * SITE_FRAME_COUNT + stage * SITE_PHASES + phase]
    }

    /// A full construction-site frame authored for the final building's
    /// footprint, progress stage, and machinery phase.
    pub fn construction(
        &self,
        kind: BuildingKind,
        faction: Faction,
        stage: usize,
        phase: usize,
    ) -> Rect {
        self.construction_row(kind, stage, phase)[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::construction`].
    pub fn construction_accent(&self, kind: BuildingKind, stage: usize, phase: usize) -> Rect {
        self.construction_row(kind, stage, phase)[ACCENT]
    }

    /// A working harvester's scoop-cycle frame: 0 is the travel pose,
    /// 1-2 the dig. Values past 2 are the caller's cycle math leaking.
    pub fn harvester_working(&self, faction: Faction, frame: usize) -> Rect {
        let f = faction_index(faction);
        match frame {
            0 => self.harvester[f],
            1 => self.harvester_scoop[0][f],
            _ => self.harvester_scoop[1][f],
        }
    }

    /// The scoop cycle's accent mask, frame-matched to
    /// [`Self::harvester_working`].
    pub fn harvester_working_accent(&self, frame: usize) -> Rect {
        match frame {
            0 => self.harvester[ACCENT],
            1 => self.harvester_scoop[0][ACCENT],
            _ => self.harvester_scoop[1][ACCENT],
        }
    }

    fn moving_unit_row(&self, kind: UnitKind, frame: usize) -> &[Rect; 3] {
        let rows = match kind {
            UnitKind::Harvester => Some(&self.harvester_tread),
            UnitKind::Sentinel => Some(&self.sentinel_move),
            UnitKind::Scuttler => Some(&self.scuttler_move),
            UnitKind::Lancer => Some(&self.lancer_move),
            UnitKind::Bombard => Some(&self.bombard_move),
            UnitKind::Flakhound => Some(&self.flakhound_tread),
            UnitKind::Stinger => Some(&self.stinger_move),
            _ => None,
        };
        rows.and_then(|rows| frame.checked_sub(1).and_then(|index| rows.get(index)))
            .unwrap_or_else(|| self.unit_row(kind))
    }

    /// A ground unit's authored locomotion phase. Air units safely return
    /// their base frame so callers need no art-specific branch.
    pub fn unit_moving(&self, kind: UnitKind, faction: Faction, frame: usize) -> Rect {
        self.moving_unit_row(kind, frame)[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::unit_moving`].
    pub fn unit_moving_accent(&self, kind: UnitKind, frame: usize) -> Rect {
        self.moving_unit_row(kind, frame)[ACCENT]
    }

    /// The construction lattice: dense early, sparse near completion.
    pub fn scaffold(&self, dense: bool) -> Rect {
        self.scaffold[if dense { 0 } else { 1 }]
    }

    /// A death-scatter hull shard.
    pub fn debris(&self, variant: usize) -> Rect {
        self.debris[variant % 3]
    }

    fn unit_row(&self, kind: UnitKind) -> &[Rect; 3] {
        match kind {
            UnitKind::Harvester => &self.harvester,
            UnitKind::Sentinel => &self.sentinel,
            UnitKind::Scuttler => &self.scuttler,
            UnitKind::Lancer => &self.lancer,
            UnitKind::Bombard => &self.bombard,
            UnitKind::Flakhound => &self.flakhound,
            UnitKind::Stinger => &self.stinger,
            UnitKind::Buzzard => &self.buzzard,
            UnitKind::Darter => &self.darter,
            UnitKind::Talon => &self.talon,
            UnitKind::Wisp => &self.wisp,
        }
    }

    /// The unit sprite region for a kind and faction.
    pub fn unit(&self, kind: UnitKind, faction: Faction) -> Rect {
        self.unit_row(kind)[faction_index(faction)]
    }

    /// The allegiance-accent mask over a unit's faction-colored
    /// regions — grayscale in the atlas, tinted at draw time.
    pub fn unit_accent(&self, kind: UnitKind) -> Rect {
        self.unit_row(kind)[ACCENT]
    }
}

/// Every clip the shell plays. Generated by `tools/gen_sounds.py`.
pub struct Sounds {
    /// An attack landing.
    pub laser: Sound,
    /// A Lancer's rail shot.
    pub rail_fire: Sound,
    /// A unit popping.
    pub unit_death: Sound,
    /// A building coming down.
    pub building_boom: Sound,
    /// Your harvester delivering.
    pub deposit: Sound,
    /// Your Foundry finishing a unit.
    pub train_done: Sound,
    /// Menu activation.
    pub click: Sound,
    /// An order was refused.
    pub denied: Sound,
    /// You won.
    pub victory: Sound,
    /// You didn't.
    pub defeat: Sound,
    /// Flak bursting against the sky.
    pub flak: Sound,
    /// An artillery shell landing.
    pub artillery_boom: Sound,
    /// The gun speaking (the boom belongs to the impact).
    pub artillery_launch: Sound,
    /// Order acknowledged.
    pub ack: Sound,
    /// The zap's lower sibling, alternated per shot.
    pub laser2: Sound,
    /// Front-end industrial ambience.
    pub music_menu: Sound,
    /// The calm match bed.
    pub music_calm: Sound,
    /// Rhythmic pressure layered over the calm bed during combat.
    pub music_combat: Sound,
    /// A neutral result bed for draws.
    pub music_result: Sound,
    /// The local-player victory bed.
    pub music_victory: Sound,
    /// The local-player defeat or surrender bed.
    pub music_defeat: Sound,
}

async fn clip(name: &str) -> Result<Sound> {
    let path = resource(&format!("assets/sounds/{name}.wav"));
    load_sound(&path)
        .await
        .with_context(|| format!("loading {path} (run from the workspace root)"))
}

impl Sounds {
    /// Loads every clip up front, like [`Sprites::load`].
    pub async fn load() -> Result<Self> {
        Ok(Self {
            laser: clip("laser").await?,
            rail_fire: clip("rail_fire").await?,
            unit_death: clip("unit_death").await?,
            building_boom: clip("building_boom").await?,
            deposit: clip("deposit").await?,
            train_done: clip("train_done").await?,
            click: clip("click").await?,
            denied: clip("denied").await?,
            victory: clip("victory").await?,
            defeat: clip("defeat").await?,
            flak: clip("flak").await?,
            artillery_boom: clip("artillery_boom").await?,
            artillery_launch: clip("artillery_launch").await?,
            ack: clip("ack").await?,
            laser2: clip("laser2").await?,
            music_menu: clip("music_menu").await?,
            music_calm: clip("music_calm").await?,
            music_combat: clip("music_combat").await?,
            music_result: clip("music_result").await?,
            music_victory: clip("music_victory").await?,
            music_defeat: clip("music_defeat").await?,
        })
    }
}

/// The asset manifest, checked without a GPU.
///
/// [`Sprites::load`] already fails loudly on a missing region and
/// [`Sprites::unit_row`] is exhaustive, so a new kind cannot compile
/// without a sprite row — but both of those checks need a window, which
/// CI never opens. These read `atlas.json` as plain data instead, so a
/// regenerated atlas that dropped a row, or a kind whose art was never
/// generated, fails by name in the ordinary test run.
#[cfg(test)]
mod tests {
    use super::*;

    const SOUND_NAMES: [&str; 21] = [
        "ack",
        "artillery_boom",
        "artillery_launch",
        "building_boom",
        "click",
        "defeat",
        "denied",
        "deposit",
        "flak",
        "laser",
        "laser2",
        "music_calm",
        "music_combat",
        "music_defeat",
        "music_menu",
        "music_result",
        "music_victory",
        "rail_fire",
        "train_done",
        "unit_death",
        "victory",
    ];

    fn manifest() -> Manifest {
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../assets/sprites/atlas.json");
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("reading {}: {err}", path.display()));
        serde_json::from_str(&text).expect("atlas.json maps names to [x, y, w, h]")
    }

    #[test]
    fn generated_sound_bank_is_complete_and_has_valid_pcm_metadata() {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../assets/sounds");
        let mut actual: Vec<String> = std::fs::read_dir(&dir)
            .expect("assets/sounds exists")
            .filter_map(|entry| entry.ok())
            .filter(|entry| entry.path().extension().and_then(|ext| ext.to_str()) == Some("wav"))
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .collect();
        actual.sort();
        let expected: Vec<String> = SOUND_NAMES
            .iter()
            .map(|name| format!("{name}.wav"))
            .collect();
        assert_eq!(
            actual, expected,
            "tools/gen_sounds.py and the checked-in bank must be a bijection"
        );

        for name in SOUND_NAMES {
            let path = dir.join(format!("{name}.wav"));
            let bytes = std::fs::read(&path)
                .unwrap_or_else(|err| panic!("reading {}: {err}", path.display()));
            assert!(
                bytes.len() >= 44,
                "{} is shorter than a WAV header",
                path.display()
            );
            assert_eq!(&bytes[0..4], b"RIFF", "{} is not RIFF", path.display());
            assert_eq!(&bytes[8..12], b"WAVE", "{} is not WAVE", path.display());
            assert_eq!(
                u16::from_le_bytes([bytes[22], bytes[23]]),
                1,
                "{} must stay mono",
                path.display()
            );
            assert_eq!(
                u32::from_le_bytes([bytes[24], bytes[25], bytes[26], bytes[27]]),
                22_050,
                "{} changed sample rate",
                path.display()
            );
            assert_eq!(
                u16::from_le_bytes([bytes[34], bytes[35]]),
                16,
                "{} must stay 16-bit PCM",
                path.display()
            );
            if name.starts_with("music_") {
                let data_bytes =
                    u32::from_le_bytes([bytes[40], bytes[41], bytes[42], bytes[43]]) as usize;
                assert_eq!(
                    data_bytes,
                    12 * 22_050 * 2,
                    "{} is not the authored twelve-second loop",
                    path.display()
                );
            }
        }
    }

    #[test]
    fn the_shell_and_the_atlas_name_the_same_sprites() {
        let atlas = manifest();
        let named = atlas_keys();
        let mut missing: Vec<&String> = named.iter().filter(|k| !atlas.contains_key(*k)).collect();
        missing.sort();
        assert!(
            missing.is_empty(),
            "the shell asks for sprites the atlas does not ship: {missing:?} \
             (regenerate with tools/gen_sprites.py)"
        );
        // The other direction: art nothing draws is art nobody blessed.
        // gen_sprites.py and the shell ship together, so a row with no
        // reader is a half-landed change, not a spare part.
        let mut orphans: Vec<&String> = atlas.keys().filter(|k| !named.contains(k)).collect();
        orphans.sort();
        assert!(
            orphans.is_empty(),
            "the atlas ships sprites the shell never draws: {orphans:?}"
        );
        // Containment both ways still allows the shell to name one
        // region twice; a bijection does not.
        assert_eq!(named.len(), atlas.len(), "a sprite is named twice");
    }

    #[test]
    fn every_kind_has_both_rosters_and_an_accent_mask() {
        let atlas = manifest();
        let stems = ALL_UNIT_KINDS
            .map(unit_stem)
            .into_iter()
            .chain(ALL_BUILDING_KINDS.map(building_stem));
        for stem in stems {
            for key in variant_keys(stem, "") {
                assert!(atlas.contains_key(&key), "no {key} in the atlas");
            }
        }
        for stem in [TURRET_BARREL_STEM, FLAK_MOUNT_STEM, BASTION_MOUNT_STEM] {
            for key in variant_keys(stem, "") {
                assert!(atlas.contains_key(&key), "no {key} in the atlas");
            }
        }
    }

    #[test]
    fn defense_mounts_match_their_footprints_and_rotate_about_square_canvases() {
        let atlas = manifest();
        for (kind, mount) in [
            (BuildingKind::Turret, TURRET_BARREL_STEM),
            (BuildingKind::FlakTurret, FLAK_MOUNT_STEM),
            (BuildingKind::Bastion, BASTION_MOUNT_STEM),
        ] {
            let base = &atlas[&variant_keys(building_stem(kind), "")[0]];
            for key in variant_keys(mount, "") {
                let rect = &atlas[&key];
                assert_eq!(
                    rect[2..],
                    base[2..],
                    "{key} must share the defense footprint"
                );
                assert_eq!(rect[2], rect[3], "{key} needs a centered rotation pivot");
            }
        }
    }

    fn sprite_image(name: &str) -> macroquad::prelude::Image {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../assets/sprites")
            .join(format!("{name}.png"));
        let bytes =
            std::fs::read(&path).unwrap_or_else(|err| panic!("reading {}: {err}", path.display()));
        macroquad::prelude::Image::from_file_with_format(
            &bytes,
            Some(macroquad::prelude::ImageFormat::Png),
        )
        .unwrap_or_else(|err| panic!("decoding {}: {err}", path.display()))
    }

    fn alpha_bytes(image: &macroquad::prelude::Image) -> impl Iterator<Item = u8> + '_ {
        image.bytes.chunks_exact(4).map(|pixel| pixel[3])
    }

    fn opaque_span(image: &macroquad::prelude::Image) -> (usize, usize) {
        let width = usize::from(image.width);
        let height = usize::from(image.height);
        let mut min_x = width;
        let mut min_y = height;
        let mut max_x = 0;
        let mut max_y = 0;
        let mut found = false;
        for (index, pixel) in image.bytes.chunks_exact(4).enumerate() {
            if pixel[3] < 64 {
                continue;
            }
            let x = index % width;
            let y = index / width;
            min_x = min_x.min(x);
            min_y = min_y.min(y);
            max_x = max_x.max(x);
            max_y = max_y.max(y);
            found = true;
        }
        assert!(found, "sprite has no opaque art");
        (max_x - min_x + 1, max_y - min_y + 1)
    }

    fn assert_animation_variant(stem: &str, suffix: &str) {
        let ferrous = sprite_image(&format!("{stem}_ferrous{suffix}"));
        let cupric = sprite_image(&format!("{stem}_cupric{suffix}"));
        let accent = sprite_image(&format!("{stem}_accent{suffix}"));
        assert_eq!(
            (ferrous.width, ferrous.height),
            (cupric.width, cupric.height),
            "{stem}{suffix} faction frames must share a footprint"
        );
        assert_eq!(
            (ferrous.width, ferrous.height),
            (accent.width, accent.height),
            "{stem}{suffix} accent must share the frame footprint"
        );
        assert_eq!(
            alpha_bytes(&ferrous).collect::<Vec<_>>(),
            alpha_bytes(&cupric).collect::<Vec<_>>(),
            "{stem}{suffix} variants must share a silhouette"
        );
        assert!(
            alpha_bytes(&accent).any(|alpha| alpha > 0),
            "{stem}{suffix} needs a non-empty allegiance mask"
        );
    }

    #[test]
    fn authored_animation_families_are_complete_distinct_and_faction_safe() {
        for (stem, suffixes) in [
            ("harvester", TREAD_SUFFIXES),
            ("sentinel", MOVE_SUFFIXES),
            ("scuttler", MOVE_SUFFIXES),
            ("lancer", MOVE_SUFFIXES),
            ("bombard", MOVE_SUFFIXES),
            ("flakhound", TREAD_SUFFIXES),
            ("stinger", MOVE_SUFFIXES),
        ] {
            let mut ferrous_seen = vec![sprite_image(&format!("{stem}_ferrous")).bytes];
            let mut cupric_seen = vec![sprite_image(&format!("{stem}_cupric")).bytes];
            for suffix in suffixes {
                assert_animation_variant(stem, suffix);
                let ferrous = sprite_image(&format!("{stem}_ferrous{suffix}")).bytes;
                let cupric = sprite_image(&format!("{stem}_cupric{suffix}")).bytes;
                assert!(
                    !ferrous_seen.contains(&ferrous),
                    "{stem}{suffix} must be distinct from every other Ferrous locomotion phase"
                );
                assert!(
                    !cupric_seen.contains(&cupric),
                    "{stem}{suffix} must be distinct from every other Cupric locomotion phase"
                );
                ferrous_seen.push(ferrous);
                cupric_seen.push(cupric);
            }
        }
        for kind in WORK_BUILDING_KINDS {
            let stem = building_stem(kind);
            let base = sprite_image(&format!("{stem}_ferrous"));
            for suffix in WORK_SUFFIXES {
                assert_animation_variant(stem, suffix);
                assert_ne!(
                    sprite_image(&format!("{stem}_ferrous{suffix}")).bytes,
                    base.bytes,
                    "{stem}{suffix} must differ from its idle pose"
                );
            }
        }
        for kind in ALL_BUILDING_KINDS {
            let stem = building_stem(kind);
            let base = sprite_image(&format!("{stem}_ferrous"));
            for stage in 0..SITE_STAGES {
                let mut phases = Vec::new();
                for phase in 0..SITE_PHASES {
                    let suffix = format!("_site{stage}_{phase}");
                    assert_animation_variant(stem, &suffix);
                    let frame = sprite_image(&format!("{stem}_ferrous{suffix}"));
                    assert_eq!(
                        (frame.width, frame.height),
                        (base.width, base.height),
                        "{stem}{suffix} must fill the final footprint"
                    );
                    phases.push(frame.bytes);
                }
                assert_ne!(
                    phases[0], phases[1],
                    "{stem} site stage {stage} must move its authored machinery"
                );
            }
        }
    }

    #[test]
    fn defense_mount_art_covers_its_pivot_and_carries_an_allegiance_mask() {
        for stem in [TURRET_BARREL_STEM, FLAK_MOUNT_STEM, BASTION_MOUNT_STEM] {
            let ferrous = sprite_image(&format!("{stem}_ferrous"));
            let cupric = sprite_image(&format!("{stem}_cupric"));
            let accent = sprite_image(&format!("{stem}_accent"));

            assert_eq!(
                (ferrous.width, ferrous.height),
                (cupric.width, cupric.height)
            );
            assert_eq!(
                (ferrous.width, ferrous.height),
                (accent.width, accent.height)
            );
            assert_eq!(
                alpha_bytes(&ferrous).collect::<Vec<_>>(),
                alpha_bytes(&cupric).collect::<Vec<_>>(),
                "{stem} variants must rotate as one silhouette"
            );

            let center = (usize::from(ferrous.height / 2) * usize::from(ferrous.width)
                + usize::from(ferrous.width / 2))
                * 4;
            assert_ne!(
                ferrous.bytes[center + 3],
                0,
                "{stem} must cover its centered rotation pivot"
            );
            assert!(
                alpha_bytes(&accent).any(|alpha| alpha > 0),
                "{stem} needs a non-empty allegiance mask"
            );
        }
    }

    #[test]
    fn specialist_defense_mounts_keep_their_heavy_silhouettes() {
        let flak = sprite_image("flak_mount_ferrous");
        let (width, height) = opaque_span(&flak);
        assert!(
            width * 4 >= usize::from(flak.width) * 3,
            "the Flak mount must stay broad enough to read as a quad battery"
        );
        assert!(
            height * 6 >= usize::from(flak.height) * 5,
            "the Flak mount must keep visible barrels and rear magazines"
        );

        let bastion = sprite_image("bastion_mount_ferrous");
        let (width, height) = opaque_span(&bastion);
        assert!(
            width * 8 >= usize::from(bastion.width) * 5,
            "the Bastion mount must keep its oversized breech"
        );
        assert!(
            height * 8 >= usize::from(bastion.height) * 7,
            "the Bastion mount must span from muzzle to loader block"
        );
    }

    #[test]
    fn every_theme_prop_row_is_tile_sized_and_ordered_like_the_lookup() {
        let atlas = manifest();
        for (row, (theme, stem)) in [
            ("rusted-yard", "rusted_yard"),
            ("cold-circuitry", "cold_circuitry"),
            ("quarry-dust", "quarry_dust"),
            ("basalt", "basalt"),
            ("slag", "slag"),
            ("verdigris", "verdigris"),
        ]
        .into_iter()
        .enumerate()
        {
            assert_eq!(theme_prop_row(theme), Some(row));
            for variant in 0..6 {
                let key = format!("theme_{stem}_{variant}");
                assert_eq!(THEME_PROP_KEYS[row * 6 + variant], key);
                assert_eq!(atlas[&key][2..], [64.0, 64.0]);
            }
        }
        assert_eq!(theme_prop_row("unknown"), None);
    }

    #[test]
    fn every_peak_neighbor_mask_has_two_full_tile_barriers() {
        let atlas = manifest();
        for mask in 0..16 {
            for variant in 0..2 {
                let key = format!("peak_barrier_{mask:02x}_{variant}");
                assert_eq!(PEAK_BARRIER_KEYS[mask * 2 + variant], key);
                assert_eq!(atlas[&key][2..], [64.0, 64.0]);
            }
        }
    }
}
