//! Sprite loading. All art comes from `assets/sprites/`, generated by
//! `tools/gen_sprites.py`; regenerate there, never edit PNGs.

use crate::game::SoundKind;
use crate::numeric;
use anyhow::{Context, Result};
use macroquad::audio::{Sound, load_sound_from_bytes};
use macroquad::prelude::{
    Color, DrawTextureParams, FilterMode, Image, Rect, Texture2D, Vec2, draw_texture_ex,
};
use oxide_sim::{BuildingKind, Faction, UnitKind};

/// Sprite regions share bounded texture pages instead of per-sprite textures.
pub struct Sprites {
    textures: Vec<Texture2D>,
    entity_lod: crate::entity_lod::EntityLod,
    page_height: f32,
    harvester_body: Option<[[Rect; 3]; 6]>,
    excavator_body: Option<[[Rect; 3]; 3]>,
    scuttler_body: Option<[[Rect; 3]; 3]>,
    tender_body: Option<[[Rect; 3]; 3]>,
    /// Hull and mount layers for every kind whose look draws a rig.
    unit_rigs: std::collections::HashMap<UnitKind, UnitRig>,
    bombard_spades: Option<[Rect; 5]>,
    scout_radar: Option<Rect>,
    array_rig: Option<ArrayRig>,
    /// Verb pictograms for cards and order chips, indexed by
    /// [`crate::panel::VerbIcon`].
    verb_icons: [Rect; 14],
    ground: [Rect; 6],
    ground_detail: [Rect; 12],
    quarry_dressing: Option<[Rect; 12]>,
    rock: [Rect; 23],
    /// Full-tile exclusion barriers, indexed `neighbor_mask * 2 + variant`.
    peak_barriers: [Rect; 32],
    /// The derelict 2x2 Extractor frame bed, drawn on unclaimed frames.
    extractor_frame: Rect,
    /// Tier hulls, keyed by (kind, tier-1) through [`Sprites::building_tiered`].
    turret_t1: [Rect; 3],
    turret_t2: [Rect; 3],
    flak_turret_t1: [Rect; 3],
    reclaimer_t1: [Rect; 3],
    reclaimer_t1_work: [[Rect; 3]; 12],
    array_t1: [Rect; 3],
    turret_barrel: [Rect; 3],
    turret_barrel_t1: [Rect; 3],
    turret_barrel_t2: [Rect; 3],
    flak_mount: [Rect; 3],
    flak_mount_t1: [Rect; 3],
    bastion_mount: [Rect; 3],
    turret_barrel_action: [[Rect; 3]; 4],
    turret_barrel_t1_action: [[Rect; 3]; 4],
    turret_barrel_t2_action: [[Rect; 3]; 4],
    flak_mount_action: [[Rect; 3]; 8],
    flak_mount_t1_action: [[Rect; 3]; 8],
    bastion_mount_action: [[Rect; 3]; 9],
    rock_skirt: Rect,
    decals: [Rect; 4],
    /// Six flat ground-dressing variants for each shipped theme.
    theme_props: [Rect; 36],
    /// Passable remnants scattered over safe ground.
    field_debris: [Rect; 10],
    /// Multi-tile industrial obstacles drawn over Rock terrain.
    ground_blockers: [Rect; 9],
    scrap_full: Rect,
    scrap_mid: Rect,
    scrap_low: Rect,
    scrap_rich: Rect,
    scorch: Rect,
    wreck_pile: Rect,
    air_shadow: Rect,
    burst: Rect,
    bastion_action: [[Rect; 3]; 9],
    array_t1_work: [[Rect; 3]; 6],
    construction: [[Rect; 3]; SITE_FRAME_COUNT * BUILDING_KIND_COUNT],
    harvester_cargo: [[Rect; 3]; 5],
    harvester_cargo_scoop: [[[Rect; 3]; 2]; 5],
    harvester_cargo_tread: [[[Rect; 3]; 2]; 5],
    /// Hull and tier-zero work art per building kind, indexed the same way.
    buildings: Vec<BuildingArt>,
    /// Chassis art per unit kind, indexed by the kind's discriminant.
    units: Vec<UnitArt>,
    scaffold: [Rect; 2],
    debris: [Rect; 3],
    excavator_cargo: [Rect; EXCAVATOR_CARGO_LEVELS],
}

fn faction_index(faction: Faction) -> usize {
    match faction {
        Faction::Ferrous => 0,
        Faction::Cupric => 1,
    }
}

/// Third slot of every faction-varied sprite row: the allegiance-accent
/// mask (the pixels where the two faction variants differ, grayscale).
const ACCENT: usize = 2;

/// The atlas manifest as `tools/gen_sprites.py` writes it.
type Manifest = std::collections::HashMap<String, [f32; 4]>;

pub(crate) struct ArrayRig {
    base: [[Rect; 3]; 2],
    rotor: [[Rect; 3]; 2],
}

impl ArrayRig {
    pub(crate) fn layers(&self, tier: u8, faction: Faction) -> [(Rect, Rect); 2] {
        let tier = usize::from(tier.min(1));
        [self.base[tier], self.rotor[tier]].map(|row| (row[faction_index(faction)], row[ACCENT]))
    }
}

fn array_rig(rects: &Manifest) -> Result<Option<ArrayRig>> {
    if !rects.keys().any(|key| key.starts_with("rig_array_")) {
        return Ok(None);
    }
    Ok(Some(ArrayRig {
        base: [
            variant_row(rects, "rig_array_t0_base", "")?,
            variant_row(rects, "rig_array_t1_base", "")?,
        ],
        rotor: [
            variant_row(rects, "rig_array_t0_rotor", "")?,
            variant_row(rects, "rig_array_t1_rotor", "")?,
        ],
    }))
}

pub(crate) struct UnitRig {
    hull: [[Rect; 3]; 3],
    mount: Vec<[Rect; 3]>,
}

impl UnitRig {
    pub(crate) fn hull(&self, faction: Faction, phase: usize) -> (Rect, Rect) {
        let row = self.hull[phase.min(2)];
        (row[faction_index(faction)], row[ACCENT])
    }

    pub(crate) fn mount(&self, faction: Faction, action: Option<usize>) -> (Rect, Rect) {
        let row = self.mount[action.map_or(0, |frame| (frame + 1).min(self.mount.len() - 1))];
        (row[faction_index(faction)], row[ACCENT])
    }
}

fn harvester_body_rows(rects: &Manifest) -> Result<Option<[[Rect; 3]; 6]>> {
    if !rects
        .keys()
        .any(|key| key.starts_with("rig_harvester_body_"))
    {
        return Ok(None);
    }
    Ok(Some(variant_rows(
        rects,
        "rig_harvester_body",
        [
            "_cargo0", "_cargo1", "_cargo2", "_cargo3", "_cargo4", "_cargo5",
        ],
    )?))
}

fn worker_body_rows(rects: &Manifest, stem: &str) -> Result<Option<[[Rect; 3]; 3]>> {
    if !rects.keys().any(|key| key.starts_with(&format!("{stem}_"))) {
        return Ok(None);
    }
    Ok(Some(variant_rows(rects, stem, ["", "_move1", "_move2"])?))
}

/// Every rig the atlas ships for a kind whose look draws one; its mount has
/// a frame per action frame.
fn unit_rigs(rects: &Manifest) -> Result<std::collections::HashMap<UnitKind, UnitRig>> {
    let mut rigs = std::collections::HashMap::new();
    for kind in UnitKind::ALL {
        if crate::look::unit(kind).rig
            && let Some(rig) = unit_rig(rects, unit_stem(kind), unit_action_suffixes(kind).len())?
        {
            rigs.insert(kind, rig);
        }
    }
    Ok(rigs)
}

fn unit_rig(rects: &Manifest, stem: &str, actions: usize) -> Result<Option<UnitRig>> {
    let prefix = format!("rig_{stem}");
    if !rects
        .keys()
        .any(|key| key.starts_with(&format!("{prefix}_")))
    {
        return Ok(None);
    }
    Ok(Some(UnitRig {
        hull: variant_rows(rects, &format!("{prefix}_hull"), ["", "_move1", "_move2"])?,
        mount: (0..=actions)
            .map(|action| {
                let suffix = if action == 0 {
                    String::new()
                } else {
                    format!("_action{action}")
                };
                variant_row(rects, &format!("{prefix}_mount"), &suffix)
            })
            .collect::<Result<_>>()?,
    }))
}

fn bombard_spade_rows(rects: &Manifest) -> Result<Option<[Rect; 5]>> {
    if !rects.keys().any(|key| key.starts_with("bombard_spades_")) {
        return Ok(None);
    }
    Ok(Some(pick(
        rects,
        [
            "bombard_spades_0",
            "bombard_spades_1",
            "bombard_spades_2",
            "bombard_spades_3",
            "bombard_spades_4",
        ],
    )?))
}

fn quarry_dressing_rows(rects: &Manifest) -> Result<Option<[Rect; 12]>> {
    if !rects.keys().any(|key| key.starts_with("quarry_dressing_")) {
        return Ok(None);
    }
    let keys: [String; 12] = std::array::from_fn(|index| format!("quarry_dressing_{index}"));
    Ok(Some(pick(rects, keys.each_ref().map(String::as_str))?))
}

/// Sprites with no faction variants: one region, one name.
const SINGLE_KEYS: [&str; 10] = [
    "rock_skirt",
    "extractor_frame",
    "scrap_full",
    "scrap_mid",
    "scrap_low",
    "scrap_rich",
    "scorch",
    "wreck_pile",
    "air_shadow",
    "burst",
];

/// Verb pictograms, ordered to match [`crate::panel::VerbIcon`].
const VERB_ICON_KEYS: [&str; 14] = [
    "icon_stop",
    "icon_move",
    "icon_advance",
    "icon_attack",
    "icon_patrol",
    "icon_harvest",
    "icon_build",
    "icon_repair",
    "icon_salvage",
    "icon_cancel",
    "icon_rally",
    "icon_idle",
    "icon_run",
    "icon_hunt",
];

const GROUND_KEYS: [&str; 6] = [
    "ground_0", "ground_1", "ground_2", "ground_3", "ground_4", "ground_5",
];

const GROUND_DETAIL_KEYS: [&str; 12] = [
    "ground_detail_0",
    "ground_detail_1",
    "ground_detail_2",
    "ground_detail_3",
    "ground_detail_4",
    "ground_detail_5",
    "ground_detail_6",
    "ground_detail_7",
    "ground_detail_8",
    "ground_detail_9",
    "ground_detail_10",
    "ground_detail_11",
];

const ROCK_KEYS: [&str; 23] = [
    "rock_0",
    "rock_1",
    "rock_2",
    "rock_3",
    "rock_jagged_crown",
    "rock_split_anvil",
    "rock_broken_tooth",
    "rock_hooked_shelf",
    "rock_three_spall",
    "rock_quarry_bite",
    "rock_fallen_fang",
    "rock_split_face",
    "rock_low_scree",
    "rock_hollow_crook",
    "rock_broken_rampart",
    "rock_twin_outcrop",
    "rock_quarry_fall",
    "rock_shattered_crown",
    "rock_split_gully",
    "rock_collapsed_cut",
    "rock_jagged_field",
    "rock_broken_bench",
    "rock_quarry_scatter",
];

const FIELD_DEBRIS_KEYS: [&str; 10] = [
    "field_debris_severed_cable",
    "field_debris_bent_service_rail",
    "field_debris_abandoned_canisters",
    "field_debris_braided_cable",
    "field_debris_fastener_spill",
    "field_debris_canister_cluster",
    "field_debris_sunken_cooling_fan",
    "field_debris_inspection_hatch",
    "field_debris_cable_tray",
    "field_debris_motor_casing",
];

const GROUND_BLOCKER_KEYS: [&str; 9] = [
    "ground_blocker_cooling_fan",
    "ground_blocker_compressor_skid",
    "ground_blocker_transformer_bank",
    "ground_blocker_exposed_gearbox",
    "ground_blocker_conveyor_drive",
    "ground_blocker_crusher_motor",
    "ground_blocker_track_assembly",
    "ground_blocker_vent_blower",
    "ground_blocker_generator_pallet",
];

/// Full-tile barriers, ordered `neighbor_mask * 2 + variant`. The mask is
/// north/east/south/west in bits 0 through 3.
const PEAK_BARRIER_KEYS: [&str; 32] = [
    "peak_barrier_00_0",
    "peak_barrier_00_1",
    "peak_barrier_01_0",
    "peak_barrier_01_1",
    "peak_barrier_02_0",
    "peak_barrier_02_1",
    "peak_barrier_03_0",
    "peak_barrier_03_1",
    "peak_barrier_04_0",
    "peak_barrier_04_1",
    "peak_barrier_05_0",
    "peak_barrier_05_1",
    "peak_barrier_06_0",
    "peak_barrier_06_1",
    "peak_barrier_07_0",
    "peak_barrier_07_1",
    "peak_barrier_08_0",
    "peak_barrier_08_1",
    "peak_barrier_09_0",
    "peak_barrier_09_1",
    "peak_barrier_0a_0",
    "peak_barrier_0a_1",
    "peak_barrier_0b_0",
    "peak_barrier_0b_1",
    "peak_barrier_0c_0",
    "peak_barrier_0c_1",
    "peak_barrier_0d_0",
    "peak_barrier_0d_1",
    "peak_barrier_0e_0",
    "peak_barrier_0e_1",
    "peak_barrier_0f_0",
    "peak_barrier_0f_1",
];

const DECAL_KEYS: [&str; 4] = ["decal_crack", "decal_plate", "decal_stain", "decal_wreck"];

/// Six flat ground-dressing sprites per shipped theme. Theme order is
/// mirrored by [`Sprites::theme_prop`].
const THEME_PROP_KEYS: [&str; 36] = [
    "theme_rusted_yard_0",
    "theme_rusted_yard_1",
    "theme_rusted_yard_2",
    "theme_rusted_yard_3",
    "theme_rusted_yard_4",
    "theme_rusted_yard_5",
    "theme_cold_circuitry_0",
    "theme_cold_circuitry_1",
    "theme_cold_circuitry_2",
    "theme_cold_circuitry_3",
    "theme_cold_circuitry_4",
    "theme_cold_circuitry_5",
    "theme_quarry_dust_0",
    "theme_quarry_dust_1",
    "theme_quarry_dust_2",
    "theme_quarry_dust_3",
    "theme_quarry_dust_4",
    "theme_quarry_dust_5",
    "theme_basalt_0",
    "theme_basalt_1",
    "theme_basalt_2",
    "theme_basalt_3",
    "theme_basalt_4",
    "theme_basalt_5",
    "theme_slag_0",
    "theme_slag_1",
    "theme_slag_2",
    "theme_slag_3",
    "theme_slag_4",
    "theme_slag_5",
    "theme_verdigris_0",
    "theme_verdigris_1",
    "theme_verdigris_2",
    "theme_verdigris_3",
    "theme_verdigris_4",
    "theme_verdigris_5",
];

fn theme_prop_row(theme: &str) -> Option<usize> {
    match theme {
        "rusted-yard" => Some(0),
        "cold-circuitry" => Some(1),
        "quarry-dust" => Some(2),
        "basalt" => Some(3),
        "slag" => Some(4),
        "verdigris" => Some(5),
        _ => None,
    }
}

const SCAFFOLD_KEYS: [&str; 2] = ["scaffold_dense", "scaffold_sparse"];

const DEBRIS_KEYS: [&str; 3] = ["debris_0", "debris_1", "debris_2"];

/// The Turret's gun is faction-varied like a unit, but belongs to no kind.
const TURRET_BARREL_STEM: &str = "turret_barrel";
const TURRET_BARREL_T1_STEM: &str = "turret_barrel_t1";
const TURRET_BARREL_T2_STEM: &str = "turret_barrel_t2";
const FLAK_MOUNT_STEM: &str = "flak_mount";
const FLAK_MOUNT_T1_STEM: &str = "flak_mount_t1";
const BASTION_MOUNT_STEM: &str = "bastion_mount";

/// The Harvester's dig frames hang off its own stem.
const SCOOP_SUFFIXES: [&str; 2] = ["_scoop1", "_scoop2"];
const TREAD_SUFFIXES: [&str; 2] = ["_tread1", "_tread2"];
const MOVE_SUFFIXES: [&str; 2] = ["_move1", "_move2"];
const ACTION_SUFFIXES_3: [&str; 3] = ["_action1", "_action2", "_action3"];
const ACTION_SUFFIXES_4: [&str; 4] = ["_action1", "_action2", "_action3", "_action4"];
const ACTION_SUFFIXES_6: [&str; 6] = [
    "_action1", "_action2", "_action3", "_action4", "_action5", "_action6",
];
const ACTION_SUFFIXES_8: [&str; 8] = [
    "_action1", "_action2", "_action3", "_action4", "_action5", "_action6", "_action7", "_action8",
];
const ACTION_SUFFIXES_9: [&str; 9] = [
    "_action1", "_action2", "_action3", "_action4", "_action5", "_action6", "_action7", "_action8",
    "_action9",
];
const WORK_SUFFIXES_4: [&str; 4] = ["_work1", "_work2", "_work3", "_work4"];
const WORK_SUFFIXES_6: [&str; 6] = ["_work1", "_work2", "_work3", "_work4", "_work5", "_work6"];
const WORK_SUFFIXES_12: [&str; 12] = [
    "_work1", "_work2", "_work3", "_work4", "_work5", "_work6", "_work7", "_work8", "_work9",
    "_work10", "_work11", "_work12",
];
const HARVESTER_CARGO_LEVELS: usize = 5;
const EXCAVATOR_CARGO_LEVELS: usize = 5;
const SITE_STAGES: usize = 3;
const SITE_PHASES: usize = 2;
const SITE_FRAME_COUNT: usize = SITE_STAGES * SITE_PHASES;
const BUILDING_KIND_COUNT: usize = BuildingKind::ALL.len();

/// One complete Harvester pose at a particular visible cargo level.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HarvesterPose {
    /// Resting chassis and tool.
    Idle,
    /// First authored tread phase.
    Tread1,
    /// Second authored tread phase.
    Tread2,
    /// Claws lowering around salvage.
    Scoop1,
    /// Claws closed on salvage.
    Scoop2,
}

/// One complete Excavator chassis pose beneath its independent cargo meter.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExcavatorPose {
    /// Resting chassis and raised milling drum.
    Idle,
    /// First authored tread phase.
    Tread1,
    /// Second authored tread phase.
    Tread2,
    /// First milling-drum work phase.
    Work1,
    /// Second milling-drum work phase.
    Work2,
    /// Third milling-drum work phase.
    Work3,
    /// Fourth milling-drum work phase.
    Work4,
}

/// The atlas stem a unit kind's rows live under.
pub(crate) fn unit_stem(kind: UnitKind) -> &'static str {
    kind.name()
}

/// The atlas stem a building kind's rows live under. Exhaustive on
/// purpose: a new kind must say where its art is before it compiles.
pub(crate) fn building_stem(kind: BuildingKind) -> &'static str {
    match kind {
        BuildingKind::Foundry => "foundry",
        BuildingKind::Turret => "turret",
        BuildingKind::Fabricator => "fabricator",
        BuildingKind::FlakTurret => "flak_turret",
        BuildingKind::Bastion => "bastion",
        BuildingKind::Array => "array",
        BuildingKind::Reclaimer => "reclaimer",
        BuildingKind::RepairBay => "repair_bay",
        BuildingKind::Extractor => "extractor",
        BuildingKind::Airworks => "airworks",
        BuildingKind::Crucible => "crucible",
        BuildingKind::Barricade => "barricade",
        BuildingKind::ScuttleCharge => "scuttle_charge",
    }
}

/// The three names every faction-varied row carries.
fn variant_keys(stem: &str, suffix: &str) -> [String; 3] {
    [
        format!("{stem}_ferrous{suffix}"),
        format!("{stem}_cupric{suffix}"),
        format!("{stem}_accent{suffix}"),
    ]
}

fn lookup(rects: &Manifest, name: &str) -> Result<Rect> {
    let [x, y, w, h] = rects
        .get(name)
        .copied()
        .with_context(|| format!("sprite {name:?} missing from atlas"))?;
    Ok(Rect::new(x, y, w, h))
}

fn pick<const N: usize>(rects: &Manifest, keys: [&str; N]) -> Result<[Rect; N]> {
    let mut out = [Rect::new(0.0, 0.0, 0.0, 0.0); N];
    for (slot, key) in out.iter_mut().zip(keys) {
        *slot = lookup(rects, key)?;
    }
    Ok(out)
}

fn variant_row(rects: &Manifest, stem: &str, suffix: &str) -> Result<[Rect; 3]> {
    let mut out = [Rect::new(0.0, 0.0, 0.0, 0.0); 3];
    for (slot, key) in out.iter_mut().zip(variant_keys(stem, suffix)) {
        *slot = lookup(rects, &key)?;
    }
    Ok(out)
}

fn variant_rows<const N: usize>(
    rects: &Manifest,
    stem: &str,
    suffixes: [&str; N],
) -> Result<[[Rect; 3]; N]> {
    let empty = [Rect::new(0.0, 0.0, 0.0, 0.0); 3];
    let mut out = [empty; N];
    for (row, suffix) in out.iter_mut().zip(suffixes) {
        *row = variant_row(rects, stem, suffix)?;
    }
    Ok(out)
}

fn harvester_cargo_rows(rects: &Manifest) -> Result<[[Rect; 3]; HARVESTER_CARGO_LEVELS]> {
    let empty = [Rect::new(0.0, 0.0, 0.0, 0.0); 3];
    let mut out = [empty; HARVESTER_CARGO_LEVELS];
    for (level, row) in out.iter_mut().enumerate() {
        *row = variant_row(rects, "harvester", &format!("_cargo{level}"))?;
    }
    Ok(out)
}

fn harvester_cargo_motion_rows(
    rects: &Manifest,
    suffixes: [&str; 2],
) -> Result<[[[Rect; 3]; 2]; HARVESTER_CARGO_LEVELS]> {
    let empty_row = [Rect::new(0.0, 0.0, 0.0, 0.0); 3];
    let mut out = [[empty_row; 2]; HARVESTER_CARGO_LEVELS];
    for (level, rows) in out.iter_mut().enumerate() {
        for (row, suffix) in rows.iter_mut().zip(suffixes) {
            *row = variant_row(rects, "harvester", &format!("_cargo{level}{suffix}"))?;
        }
    }
    Ok(out)
}

fn excavator_cargo_rows(rects: &Manifest) -> Result<[Rect; EXCAVATOR_CARGO_LEVELS]> {
    let mut out = [Rect::new(0.0, 0.0, 0.0, 0.0); EXCAVATOR_CARGO_LEVELS];
    for (level, rect) in out.iter_mut().enumerate() {
        *rect = lookup(rects, &format!("excavator_cargo{level}"))?;
    }
    Ok(out)
}

/// One unit kind's chassis art: the ready row, its two locomotion poses, and
/// however many action frames its atlas bank ships.
struct UnitArt {
    base: [Rect; 3],
    moving: [[Rect; 3]; 2],
    action: Vec<[Rect; 3]>,
}

/// Loads every kind's art in discriminant order, so accessors can index by
/// `kind as usize`.
fn unit_art(rects: &Manifest) -> Result<Vec<UnitArt>> {
    UnitKind::ALL
        .iter()
        .enumerate()
        .map(|(index, &kind)| {
            anyhow::ensure!(
                kind as usize == index,
                "UnitKind::ALL must list {kind:?} at its discriminant"
            );
            let stem = unit_stem(kind);
            Ok(UnitArt {
                base: variant_row(rects, stem, "")?,
                moving: variant_rows(rects, stem, unit_move_suffixes(kind))?,
                action: unit_action_suffixes(kind)
                    .iter()
                    .map(|suffix| variant_row(rects, stem, suffix))
                    .collect::<Result<_>>()?,
            })
        })
        .collect()
}

/// The two locomotion poses: tracked hulls ship tread frames, everything
/// else ships move frames.
fn unit_move_suffixes(kind: UnitKind) -> [&'static str; 2] {
    match crate::look::unit(kind).move_rows {
        crate::look::MoveRows::Tread => TREAD_SUFFIXES,
        crate::look::MoveRows::Move => MOVE_SUFFIXES,
    }
}

/// How many action frames a kind's atlas bank ships.
#[cfg(test)]
pub(crate) fn unit_action_frames(kind: UnitKind) -> usize {
    unit_action_suffixes(kind).len()
}

fn unit_action_suffixes(kind: UnitKind) -> &'static [&'static str] {
    match kind {
        UnitKind::Harvester => &[],
        UnitKind::Sentinel
        | UnitKind::Scuttler
        | UnitKind::Stinger
        | UnitKind::Buzzard
        | UnitKind::Darter
        | UnitKind::Talon
        | UnitKind::Wisp => &ACTION_SUFFIXES_4,
        UnitKind::Lancer | UnitKind::Bombard => &ACTION_SUFFIXES_6,
        UnitKind::Flakhound => &ACTION_SUFFIXES_9,
        UnitKind::Warden
        | UnitKind::Shrike
        | UnitKind::Sylph
        | UnitKind::Tender
        | UnitKind::Excavator
        | UnitKind::Condor
        | UnitKind::Breaker
        | UnitKind::Avalanche
        | UnitKind::Skyhook => &ACTION_SUFFIXES_4,
        UnitKind::Sapper => &ACTION_SUFFIXES_3,
        UnitKind::Moth => &ACTION_SUFFIXES_6,
        UnitKind::Kestrel | UnitKind::Gnat => &[],
    }
}

/// One building kind's base hull and the activity frames its tier-zero bank
/// ships. Upgraded hulls and their work rows stay named fields.
struct BuildingArt {
    base: [Rect; 3],
    work: Vec<[Rect; 3]>,
}

/// Loads every kind's art in discriminant order, like [`unit_art`].
fn building_art(rects: &Manifest) -> Result<Vec<BuildingArt>> {
    BuildingKind::ALL
        .iter()
        .enumerate()
        .map(|(index, &kind)| {
            anyhow::ensure!(
                kind as usize == index,
                "BuildingKind::ALL must list {kind:?} at its discriminant"
            );
            let stem = building_stem(kind);
            Ok(BuildingArt {
                base: variant_row(rects, stem, "")?,
                work: building_work_suffixes(kind)
                    .iter()
                    .map(|suffix| variant_row(rects, stem, suffix))
                    .collect::<Result<_>>()?,
            })
        })
        .collect()
}

fn building_work_suffixes(kind: BuildingKind) -> &'static [&'static str] {
    match kind {
        BuildingKind::Fabricator | BuildingKind::RepairBay | BuildingKind::Extractor => {
            &WORK_SUFFIXES_4
        }
        BuildingKind::Array => &WORK_SUFFIXES_6,
        BuildingKind::Reclaimer => &WORK_SUFFIXES_12,
        BuildingKind::Crucible => &WORK_SUFFIXES_4,
        BuildingKind::Foundry => &WORK_SUFFIXES_12,
        BuildingKind::Airworks => &WORK_SUFFIXES_4,
        BuildingKind::Turret
        | BuildingKind::FlakTurret
        | BuildingKind::Bastion
        | BuildingKind::Barricade
        | BuildingKind::ScuttleCharge => &[],
    }
}

fn construction_rows(
    rects: &Manifest,
) -> Result<[[Rect; 3]; SITE_FRAME_COUNT * BUILDING_KIND_COUNT]> {
    let empty = [Rect::new(0.0, 0.0, 0.0, 0.0); 3];
    let mut out = [empty; SITE_FRAME_COUNT * BUILDING_KIND_COUNT];
    for kind in BuildingKind::ALL {
        for stage in 0..SITE_STAGES {
            for phase in 0..SITE_PHASES {
                let frame = stage * SITE_PHASES + phase;
                let suffix = format!("_site{stage}_{phase}");
                out[kind as usize * SITE_FRAME_COUNT + frame] =
                    variant_row(rects, building_stem(kind), &suffix)?;
            }
        }
    }
    Ok(out)
}

/// Every key accepted in the generated production atlas, including legacy
/// compatibility aliases that remain in the generator output.
#[cfg(test)]
fn atlas_keys(atlas: &Manifest) -> Vec<String> {
    let mut keys: Vec<String> = SINGLE_KEYS
        .iter()
        .chain(VERB_ICON_KEYS.iter())
        .chain(GROUND_KEYS.iter())
        .chain(GROUND_DETAIL_KEYS.iter())
        .chain(ROCK_KEYS.iter())
        .chain(PEAK_BARRIER_KEYS.iter())
        .chain(DECAL_KEYS.iter())
        .chain(THEME_PROP_KEYS.iter())
        .chain(FIELD_DEBRIS_KEYS.iter())
        .chain(GROUND_BLOCKER_KEYS.iter())
        .chain(SCAFFOLD_KEYS.iter())
        .chain(DEBRIS_KEYS.iter())
        .map(|key| (*key).to_string())
        .collect();
    keys.extend((0..5).map(|phase| format!("bombard_spades_{phase}")));
    keys.push("scout_radar".to_owned());
    if atlas
        .keys()
        .any(|key| key.starts_with("rig_harvester_body_"))
    {
        for cargo in 0..6 {
            keys.extend(variant_keys(
                "rig_harvester_body",
                &format!("_cargo{cargo}"),
            ));
        }
    }
    for stem in ["rig_excavator_body", "rig_tender_body", "rig_scuttler_body"] {
        if atlas.keys().any(|key| key.starts_with(stem)) {
            for suffix in ["", "_move1", "_move2"] {
                keys.extend(variant_keys(stem, suffix));
            }
        }
    }
    keys.extend((0..12).map(|index| format!("quarry_dressing_{index}")));
    for (stem, action_count) in UnitKind::ALL
        .into_iter()
        .filter(|kind| crate::look::unit(*kind).rig)
        .map(|kind| (unit_stem(kind), unit_action_suffixes(kind).len()))
    {
        for suffix in ["", "_move1", "_move2"] {
            keys.extend(variant_keys(&format!("rig_{stem}_hull"), suffix));
        }
        keys.extend(variant_keys(&format!("rig_{stem}_mount"), ""));
        for action in 1..=action_count {
            keys.extend(variant_keys(
                &format!("rig_{stem}_mount"),
                &format!("_action{action}"),
            ));
        }
    }
    for tier in 0..2 {
        for part in ["base", "rotor"] {
            keys.extend(variant_keys(&format!("rig_array_t{tier}_{part}"), ""));
        }
    }

    for stem in [
        TURRET_BARREL_STEM,
        TURRET_BARREL_T1_STEM,
        TURRET_BARREL_T2_STEM,
    ] {
        keys.extend(variant_keys(stem, ""));
    }
    for stem in [
        "turret_t1",
        "turret_t2",
        "flak_turret_t1",
        "reclaimer_t1",
        "array_t1",
    ] {
        keys.extend(variant_keys(stem, ""));
    }
    for suffix in WORK_SUFFIXES_12 {
        keys.extend(variant_keys("reclaimer_t1", suffix));
    }
    for suffix in WORK_SUFFIXES_6 {
        keys.extend(variant_keys("array_t1", suffix));
    }
    keys.extend(variant_keys(FLAK_MOUNT_STEM, ""));
    keys.extend(variant_keys(FLAK_MOUNT_T1_STEM, ""));
    keys.extend(variant_keys(BASTION_MOUNT_STEM, ""));
    for stem in [
        TURRET_BARREL_STEM,
        TURRET_BARREL_T1_STEM,
        TURRET_BARREL_T2_STEM,
    ] {
        for suffix in ACTION_SUFFIXES_4 {
            keys.extend(variant_keys(stem, suffix));
        }
    }
    for suffix in ACTION_SUFFIXES_8 {
        keys.extend(variant_keys(FLAK_MOUNT_STEM, suffix));
        keys.extend(variant_keys(FLAK_MOUNT_T1_STEM, suffix));
    }
    for suffix in ACTION_SUFFIXES_9 {
        keys.extend(variant_keys(BASTION_MOUNT_STEM, suffix));
        keys.extend(variant_keys(building_stem(BuildingKind::Bastion), suffix));
    }
    for kind in UnitKind::ALL {
        let stem = unit_stem(kind);
        keys.extend(variant_keys(stem, ""));
        for suffix in unit_move_suffixes(kind) {
            keys.extend(variant_keys(stem, suffix));
        }
        for suffix in unit_action_suffixes(kind) {
            keys.extend(variant_keys(stem, suffix));
        }
    }
    for suffix in SCOOP_SUFFIXES {
        keys.extend(variant_keys(unit_stem(UnitKind::Harvester), suffix));
    }
    for level in 0..HARVESTER_CARGO_LEVELS {
        keys.extend(variant_keys("harvester", &format!("_cargo{level}")));
        for suffix in TREAD_SUFFIXES.into_iter().chain(SCOOP_SUFFIXES) {
            keys.extend(variant_keys("harvester", &format!("_cargo{level}{suffix}")));
        }
    }
    for level in 0..EXCAVATOR_CARGO_LEVELS {
        keys.push(format!("excavator_cargo{level}"));
    }
    for kind in BuildingKind::ALL {
        keys.extend(variant_keys(building_stem(kind), ""));
        for suffix in building_work_suffixes(kind) {
            keys.extend(variant_keys(building_stem(kind), suffix));
        }
        for stage in 0..SITE_STAGES {
            for phase in 0..SITE_PHASES {
                keys.extend(variant_keys(
                    building_stem(kind),
                    &format!("_site{stage}_{phase}"),
                ));
            }
        }
    }
    keys
}

/// Where game data lives: inside a packaged bundle (see
/// [`crate::paths::bundle_resources`]), or the workspace root for
/// development runs.
pub fn resource_root() -> std::path::PathBuf {
    // Native automation runs from an isolated writable directory so
    // local replays and screenshots cannot perturb a golden walk. It
    // points back at the read-only workspace resources explicitly.
    if let Some(root) = std::env::var_os("OXIDE_RESOURCE_ROOT") {
        return root.into();
    }
    crate::paths::bundle_resources().unwrap_or_else(|| std::path::PathBuf::from("."))
}

/// Reads one bundled resource. Resources load as bytes through the
/// filesystem because macroquad's own loaders resolve paths through
/// the app bundle's resource lookup on iOS, which rejects absolute
/// paths.
fn read_resource(path: &std::path::Path) -> Result<Vec<u8>> {
    std::fs::read(path).with_context(|| format!("reading {}", path.display()))
}

/// Reads and decodes a bundled image.
pub(crate) fn load_resource_image(rel: &str) -> Result<Image> {
    let bytes = read_resource(&resource_root().join(rel))?;
    Image::from_file_with_format(&bytes, None).with_context(|| format!("decoding {rel}"))
}

fn atlas_page(mut source: Rect, page_height: f32) -> (usize, Rect) {
    let page = numeric::to_usize(source.y / page_height);
    source.y -= page as f32 * page_height;
    (page, source)
}

impl Sprites {
    /// Loads the atlas up front; a missing or incomplete atlas is a
    /// startup error, not a mid-game pop.
    pub fn load() -> Result<Self> {
        let texture = Texture2D::from_image(
            &load_resource_image("assets/sprites/atlas.png")
                .context("loading assets/sprites/atlas.png (run from the workspace root)")?,
        );
        let manifest = String::from_utf8(read_resource(
            &resource_root().join("assets/sprites/atlas.json"),
        )?)
        .context("loading assets/sprites/atlas.json")?;
        let rects: Manifest = serde_json::from_str(&manifest).context("parsing atlas manifest")?;
        let page_height = texture.height();
        let page_count = rects
            .values()
            .map(|row| atlas_page(Rect::new(row[0], row[1], row[2], row[3]), page_height).0 + 1)
            .max()
            .unwrap_or(1);
        texture.set_filter(FilterMode::Nearest);
        let mut textures = vec![texture];
        for page in 1..page_count {
            let name = format!("assets/sprites/atlas_{page}.png");
            let texture = Texture2D::from_image(
                &load_resource_image(&name).with_context(|| format!("loading {name}"))?,
            );
            texture.set_filter(FilterMode::Nearest);
            textures.push(texture);
        }

        let [
            rock_skirt,
            extractor_frame,
            scrap_full,
            scrap_mid,
            scrap_low,
            scrap_rich,
            scorch,
            wreck_pile,
            air_shadow,
            burst,
        ] = pick(&rects, SINGLE_KEYS)?;
        let entity_lod = crate::entity_lod::EntityLod::load(&rects, page_height)?;
        Ok(Self {
            unit_rigs: unit_rigs(&rects)?,
            bombard_spades: bombard_spade_rows(&rects)?,
            array_rig: array_rig(&rects)?,
            scout_radar: rects
                .get("scout_radar")
                .map(|&[x, y, w, h]| Rect::new(x, y, w, h)),
            textures,
            entity_lod,
            harvester_body: harvester_body_rows(&rects)?,
            excavator_body: worker_body_rows(&rects, "rig_excavator_body")?,
            scuttler_body: worker_body_rows(&rects, "rig_scuttler_body")?,
            tender_body: worker_body_rows(&rects, "rig_tender_body")?,
            page_height,
            verb_icons: pick(&rects, VERB_ICON_KEYS)?,
            ground: pick(&rects, GROUND_KEYS)?,
            ground_detail: pick(&rects, GROUND_DETAIL_KEYS)?,
            quarry_dressing: quarry_dressing_rows(&rects)?,
            rock: pick(&rects, ROCK_KEYS)?,
            peak_barriers: pick(&rects, PEAK_BARRIER_KEYS)?,
            extractor_frame,
            turret_t1: variant_row(&rects, "turret_t1", "")?,
            turret_t2: variant_row(&rects, "turret_t2", "")?,
            flak_turret_t1: variant_row(&rects, "flak_turret_t1", "")?,
            reclaimer_t1: variant_row(&rects, "reclaimer_t1", "")?,
            reclaimer_t1_work: variant_rows(&rects, "reclaimer_t1", WORK_SUFFIXES_12)?,
            array_t1: variant_row(&rects, "array_t1", "")?,
            turret_barrel: variant_row(&rects, TURRET_BARREL_STEM, "")?,
            turret_barrel_t1: variant_row(&rects, TURRET_BARREL_T1_STEM, "")?,
            turret_barrel_t2: variant_row(&rects, TURRET_BARREL_T2_STEM, "")?,
            flak_mount: variant_row(&rects, FLAK_MOUNT_STEM, "")?,
            flak_mount_t1: variant_row(&rects, FLAK_MOUNT_T1_STEM, "")?,
            bastion_mount: variant_row(&rects, BASTION_MOUNT_STEM, "")?,
            turret_barrel_action: variant_rows(&rects, TURRET_BARREL_STEM, ACTION_SUFFIXES_4)?,
            turret_barrel_t1_action: variant_rows(
                &rects,
                TURRET_BARREL_T1_STEM,
                ACTION_SUFFIXES_4,
            )?,
            turret_barrel_t2_action: variant_rows(
                &rects,
                TURRET_BARREL_T2_STEM,
                ACTION_SUFFIXES_4,
            )?,
            flak_mount_action: variant_rows(&rects, FLAK_MOUNT_STEM, ACTION_SUFFIXES_8)?,
            flak_mount_t1_action: variant_rows(&rects, FLAK_MOUNT_T1_STEM, ACTION_SUFFIXES_8)?,
            bastion_mount_action: variant_rows(&rects, BASTION_MOUNT_STEM, ACTION_SUFFIXES_9)?,
            rock_skirt,
            decals: pick(&rects, DECAL_KEYS)?,
            theme_props: pick(&rects, THEME_PROP_KEYS)?,
            field_debris: pick(&rects, FIELD_DEBRIS_KEYS)?,
            ground_blockers: pick(&rects, GROUND_BLOCKER_KEYS)?,
            scrap_full,
            scrap_mid,
            scrap_low,
            scrap_rich,
            scorch,
            wreck_pile,
            air_shadow,
            burst,
            bastion_action: variant_rows(&rects, "bastion", ACTION_SUFFIXES_9)?,
            array_t1_work: variant_rows(&rects, "array_t1", WORK_SUFFIXES_6)?,
            construction: construction_rows(&rects)?,
            harvester_cargo: harvester_cargo_rows(&rects)?,
            harvester_cargo_scoop: harvester_cargo_motion_rows(&rects, SCOOP_SUFFIXES)?,
            harvester_cargo_tread: harvester_cargo_motion_rows(&rects, TREAD_SUFFIXES)?,
            buildings: building_art(&rects)?,
            units: unit_art(&rects)?,
            scaffold: pick(&rects, SCAFFOLD_KEYS)?,
            debris: pick(&rects, DEBRIS_KEYS)?,
            excavator_cargo: excavator_cargo_rows(&rects)?,
        })
    }

    pub(crate) fn harvester_body(&self, faction: Faction, cargo: usize) -> Option<(Rect, Rect)> {
        self.harvester_body.as_ref().map(|rows| {
            let row = rows[cargo.min(5)];
            (row[faction_index(faction)], row[ACCENT])
        })
    }

    pub(crate) fn worker_body(
        &self,
        kind: UnitKind,
        faction: Faction,
        cargo: usize,
        phase: usize,
    ) -> Option<(Rect, Rect)> {
        let rows = match crate::look::unit(kind).tool? {
            crate::look::WorkerTool::Scoop => return self.harvester_body(faction, cargo),
            crate::look::WorkerTool::Drum => self.excavator_body.as_ref()?,
            crate::look::WorkerTool::Shears => self.scuttler_body.as_ref()?,
            crate::look::WorkerTool::Welder => self.tender_body.as_ref()?,
        };
        let row = rows[phase.min(2)];
        Some((row[faction_index(faction)], row[ACCENT]))
    }

    pub(crate) fn sprite_contact(
        &self,
        source: Rect,
        from: Vec2,
        aim: Vec2,
        origin: Vec2,
        size: Vec2,
    ) -> Option<Vec2> {
        self.entity_lod.contact(source, from, aim, origin, size)
    }

    /// Draw an atlas region from its page while preserving its authored canvas.
    pub fn draw(&self, x: f32, y: f32, tint: Color, mut params: DrawTextureParams) {
        if tint.a <= 0.0 {
            return;
        }
        if self
            .entity_lod
            .draw(macroquad::prelude::vec2(x, y), tint, &params)
        {
            return;
        }
        let page = if let Some(source) = params.source {
            let (page, local) = atlas_page(source, self.page_height);
            params.source = Some(local);
            page
        } else {
            0
        };
        draw_texture_ex(&self.textures[page], x, y, tint, params);
    }

    pub fn draw_unit(&self, x: f32, y: f32, tint: Color, params: DrawTextureParams, zoom: f32) {
        let tint = Color {
            a: tint.a * (1.0 - crate::strategic_markers::marker_alpha(zoom)),
            ..tint
        };
        self.draw(x, y, tint, params);
    }

    pub fn draw_building(&self, x: f32, y: f32, tint: Color, params: DrawTextureParams, zoom: f32) {
        let fade = 1.0 - 0.45 * crate::strategic_markers::marker_alpha(zoom);
        self.draw(
            x,
            y,
            Color {
                r: tint.r * fade,
                g: tint.g * fade,
                b: tint.b * fade,
                ..tint
            },
            params,
        );
    }

    pub fn draw_portrait(&self, dest: Rect, layers: &[(Rect, Color)]) {
        use macroquad::prelude::*;
        let bounds = layers
            .iter()
            .map(|(source, _)| self.entity_lod.bounds(*source))
            .reduce(macroquad::math::Rect::combine_with)
            .unwrap_or(Rect::new(0.0, 0.0, 1.0, 1.0));
        let inset = dest.w.min(dest.h) * 0.05;
        let extent =
            (dest.w - 2.0 * inset).min(dest.h - 2.0 * inset) / bounds.w.max(bounds.h).max(0.01);
        let dpi = screen_dpi_scale();
        let x =
            ((dest.x + dest.w * 0.5 - (bounds.x + bounds.w * 0.5) * extent) * dpi).round() / dpi;
        let y =
            ((dest.y + dest.h * 0.5 - (bounds.y + bounds.h * 0.5) * extent) * dpi).round() / dpi;
        let extent = (extent * dpi).round() / dpi;
        self.draw_canvas(Rect::new(x, y, extent, extent), layers);
    }

    /// Compose layers in a shared authored canvas without portrait cropping.
    pub fn draw_canvas(&self, dest: Rect, layers: &[(Rect, Color)]) {
        for &(source, tint) in layers {
            self.draw(
                dest.x,
                dest.y,
                tint,
                DrawTextureParams {
                    source: Some(source),
                    dest_size: Some(macroquad::prelude::vec2(dest.w, dest.h)),
                    ..Default::default()
                },
            );
        }
    }

    /// A verb pictogram's atlas region.
    pub fn verb_icon(&self, icon: crate::panel::VerbIcon) -> Rect {
        self.verb_icons[icon as usize]
    }

    /// A ground variant's atlas region.
    pub fn ground(&self, variant: usize) -> Rect {
        self.ground[variant % self.ground.len()]
    }

    /// A ground grit-and-crack overlay's atlas region.
    pub fn ground_detail(&self, variant: usize) -> Rect {
        self.ground_detail[variant % self.ground_detail.len()]
    }

    pub fn ground_detail_count(&self) -> usize {
        self.ground_detail.len()
    }

    pub(crate) fn quarry_dressing(&self, variant: usize) -> Option<Rect> {
        self.quarry_dressing.map(|row| row[variant % row.len()])
    }

    /// A rock variant's atlas region.
    pub fn rock(&self, variant: usize) -> Rect {
        self.rock[variant % self.rock.len()]
    }

    /// A passable, flat remnant's atlas region.
    pub fn field_debris(&self, variant: usize) -> Rect {
        self.field_debris[variant % self.field_debris.len()]
    }

    /// A raised industrial obstacle's atlas region.
    pub fn ground_blocker(&self, variant: usize) -> Rect {
        self.ground_blockers[variant % self.ground_blockers.len()]
    }

    fn turret_mount_row(&self, tier: u8) -> &[Rect; 3] {
        match tier {
            1 => &self.turret_barrel_t1,
            2 => &self.turret_barrel_t2,
            _ => &self.turret_barrel,
        }
    }

    /// A defense's tier-appropriate directional mount, if its base art ships bare.
    pub fn defense_mount(
        &self,
        kind: BuildingKind,
        tier: u8,
        faction: oxide_sim::Faction,
    ) -> Option<Rect> {
        let row = match kind {
            BuildingKind::Turret => self.turret_mount_row(tier),
            BuildingKind::FlakTurret if tier == 1 => &self.flak_mount_t1,
            BuildingKind::FlakTurret => &self.flak_mount,
            BuildingKind::Bastion => &self.bastion_mount,
            _ => return None,
        };
        Some(row[faction_index(faction)])
    }

    /// The allegiance-accent mask matched to [`Self::defense_mount`].
    pub fn defense_mount_accent(&self, kind: BuildingKind, tier: u8) -> Option<Rect> {
        let row = match kind {
            BuildingKind::Turret => self.turret_mount_row(tier),
            BuildingKind::FlakTurret if tier == 1 => &self.flak_mount_t1,
            BuildingKind::FlakTurret => &self.flak_mount,
            BuildingKind::Bastion => &self.bastion_mount,
            _ => return None,
        };
        Some(row[ACCENT])
    }

    fn defense_mount_action_row(
        &self,
        kind: BuildingKind,
        tier: u8,
        frame: usize,
    ) -> Option<&[Rect; 3]> {
        match kind {
            BuildingKind::Turret => match tier {
                1 => self.turret_barrel_t1_action.get(frame),
                2 => self.turret_barrel_t2_action.get(frame),
                _ => self.turret_barrel_action.get(frame),
            },
            BuildingKind::FlakTurret if tier == 1 => self.flak_mount_t1_action.get(frame),
            BuildingKind::FlakTurret => self.flak_mount_action.get(frame),
            BuildingKind::Bastion => self.bastion_mount_action.get(frame),
            _ => None,
        }
    }

    /// A defense mount's zero-based authored action frame. An out-of-range
    /// frame falls back to the ready mount; unarmed buildings return `None`.
    pub fn defense_mount_action(
        &self,
        kind: BuildingKind,
        tier: u8,
        faction: Faction,
        frame: usize,
    ) -> Option<Rect> {
        self.defense_mount_action_row(kind, tier, frame)
            .map(|row| row[faction_index(faction)])
            .or_else(|| self.defense_mount(kind, tier, faction))
    }

    /// The allegiance mask matched to [`Self::defense_mount_action`].
    pub fn defense_mount_action_accent(
        &self,
        kind: BuildingKind,
        tier: u8,
        frame: usize,
    ) -> Option<Rect> {
        self.defense_mount_action_row(kind, tier, frame)
            .map(|row| row[ACCENT])
            .or_else(|| self.defense_mount_accent(kind, tier))
    }

    /// A full-tile exclusion barrier connected to its peak neighbors.
    pub fn peak_barrier(&self, neighbor_mask: u8, variant: usize) -> Rect {
        self.peak_barriers[usize::from(neighbor_mask & 0x0f) * 2 + variant % 2]
    }

    /// The derelict Extractor frame bed (2x2 tiles).
    pub fn extractor_frame(&self) -> Rect {
        self.extractor_frame
    }

    /// The soft shadow a rock casts on a neighboring ground tile
    /// (authored falling from the top edge; rotate toward the rock).
    pub fn rock_skirt(&self) -> Rect {
        self.rock_skirt
    }

    /// A ground decal's atlas region.
    pub fn decal(&self, variant: usize) -> Rect {
        self.decals[variant % self.decals.len()]
    }

    /// A flat ground-dressing sprite for a shipped map theme.
    pub fn theme_prop(&self, theme: &str, variant: usize) -> Option<Rect> {
        let row = theme_prop_row(theme)?;
        Some(self.theme_props[row * 6 + variant % 6])
    }

    /// The scrap sprite region for a remaining amount: anything above a
    /// standard node renders as the rich pile, then thirds of standard.
    pub fn scrap(&self, amount: u32, standard_amount: u32) -> Rect {
        if amount > standard_amount {
            self.scrap_rich
        } else if amount * 3 > standard_amount * 2 {
            self.scrap_full
        } else if amount * 3 > standard_amount {
            self.scrap_mid
        } else {
            self.scrap_low
        }
    }

    /// The building-death scorch decal region.
    pub fn scorch(&self) -> Rect {
        self.scorch
    }

    /// A wreck salvage pile on open ground.
    pub fn wreck_pile(&self) -> Rect {
        self.wreck_pile
    }

    /// The soft shadow a flyer casts on the ground.
    pub fn air_shadow(&self) -> Rect {
        self.air_shadow
    }

    /// The splash-detonation frame.
    pub fn burst(&self) -> Rect {
        self.burst
    }

    /// The building sprite region for a kind and faction.
    fn building_row(&self, kind: oxide_sim::BuildingKind) -> &[Rect; 3] {
        &self.buildings[kind as usize].base
    }

    pub fn building(&self, kind: oxide_sim::BuildingKind, faction: Faction) -> Rect {
        self.building_row(kind)[faction_index(faction)]
    }

    /// A tier's hull row, when the ladder rung has authored art;
    /// otherwise the base hull carries every rung.
    fn tier_row(&self, kind: BuildingKind, tier: u8) -> Option<&[Rect; 3]> {
        match (kind, tier) {
            (BuildingKind::Turret, 1) => Some(&self.turret_t1),
            (BuildingKind::Turret, 2) => Some(&self.turret_t2),
            (BuildingKind::FlakTurret, 1) => Some(&self.flak_turret_t1),
            (BuildingKind::Reclaimer, 1) => Some(&self.reclaimer_t1),
            (BuildingKind::Array, 1) => Some(&self.array_t1),
            _ => None,
        }
    }

    /// The hull for a building at its upgrade-ladder rung.
    pub fn building_tiered(
        &self,
        kind: oxide_sim::BuildingKind,
        tier: u8,
        faction: Faction,
    ) -> Rect {
        self.tier_row(kind, tier)
            .unwrap_or_else(|| self.building_row(kind))[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::building_tiered`].
    pub fn building_tiered_accent(&self, kind: oxide_sim::BuildingKind, tier: u8) -> Rect {
        self.tier_row(kind, tier)
            .unwrap_or_else(|| self.building_row(kind))[ACCENT]
    }

    /// The allegiance-accent mask over a building's faction-colored
    /// regions: grayscale in the atlas, tinted at draw time.
    pub fn building_accent(&self, kind: oxide_sim::BuildingKind) -> Rect {
        self.building_row(kind)[ACCENT]
    }

    fn building_action_row(&self, kind: BuildingKind, frame: usize) -> Option<&[Rect; 3]> {
        match kind {
            BuildingKind::Bastion => self.bastion_action.get(frame),
            _ => None,
        }
    }

    /// A building base's zero-based authored action frame. Bastion charge
    /// cells live here; other building bases and invalid frames stay ready.
    pub fn building_action(&self, kind: BuildingKind, faction: Faction, frame: usize) -> Rect {
        self.building_action_row(kind, frame)
            .unwrap_or_else(|| self.building_row(kind))[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::building_action`].
    pub fn building_action_accent(&self, kind: BuildingKind, frame: usize) -> Rect {
        self.building_action_row(kind, frame)
            .unwrap_or_else(|| self.building_row(kind))[ACCENT]
    }

    fn building_work_row(&self, kind: BuildingKind, tier: u8, frame: usize) -> Option<&[Rect; 3]> {
        let rows: &[[Rect; 3]] = match (kind, tier) {
            (BuildingKind::Reclaimer, 1) => &self.reclaimer_t1_work,
            (BuildingKind::Array, 1) => &self.array_t1_work,
            (_, 0) => &self.buildings[kind as usize].work,
            _ => return None,
        };
        frame.checked_sub(1).and_then(|index| rows.get(index))
    }

    /// A complete authored activity frame for a working building. Frame 0
    /// is the ordinary base art and is also the reduced-motion pose.
    pub fn building_working(
        &self,
        kind: BuildingKind,
        tier: u8,
        faction: Faction,
        frame: usize,
    ) -> Rect {
        self.building_work_row(kind, tier, frame)
            .or_else(|| self.tier_row(kind, tier))
            .unwrap_or_else(|| self.building_row(kind))[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::building_working`].
    pub fn building_working_accent(&self, kind: BuildingKind, tier: u8, frame: usize) -> Rect {
        self.building_work_row(kind, tier, frame)
            .or_else(|| self.tier_row(kind, tier))
            .unwrap_or_else(|| self.building_row(kind))[ACCENT]
    }

    fn construction_row(&self, kind: BuildingKind, stage: usize, phase: usize) -> &[Rect; 3] {
        let stage = stage.min(SITE_STAGES - 1);
        let phase = phase.min(SITE_PHASES - 1);
        &self.construction[kind as usize * SITE_FRAME_COUNT + stage * SITE_PHASES + phase]
    }

    /// A full construction-site frame authored for the final building's
    /// footprint, progress stage, and machinery phase.
    pub fn construction(
        &self,
        kind: BuildingKind,
        faction: Faction,
        stage: usize,
        phase: usize,
    ) -> Rect {
        self.construction_row(kind, stage, phase)[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::construction`].
    pub fn construction_accent(&self, kind: BuildingKind, stage: usize, phase: usize) -> Rect {
        self.construction_row(kind, stage, phase)[ACCENT]
    }

    fn harvester_frame_row(&self, cargo: usize, pose: HarvesterPose) -> &[Rect; 3] {
        let cargo = cargo.min(HARVESTER_CARGO_LEVELS - 1);
        match pose {
            HarvesterPose::Idle => &self.harvester_cargo[cargo],
            HarvesterPose::Tread1 => &self.harvester_cargo_tread[cargo][0],
            HarvesterPose::Tread2 => &self.harvester_cargo_tread[cargo][1],
            HarvesterPose::Scoop1 => &self.harvester_cargo_scoop[cargo][0],
            HarvesterPose::Scoop2 => &self.harvester_cargo_scoop[cargo][1],
        }
    }

    /// A complete Harvester frame with its integral cargo meter. Cargo
    /// values above four clamp to the full bay.
    pub fn harvester_frame(&self, faction: Faction, cargo: usize, pose: HarvesterPose) -> Rect {
        self.harvester_frame_row(cargo, pose)[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::harvester_frame`].
    pub fn harvester_frame_accent(&self, cargo: usize, pose: HarvesterPose) -> Rect {
        self.harvester_frame_row(cargo, pose)[ACCENT]
    }

    fn excavator_frame_row(&self, pose: ExcavatorPose) -> &[Rect; 3] {
        let art = &self.units[UnitKind::Excavator as usize];
        match pose {
            ExcavatorPose::Idle => &art.base,
            ExcavatorPose::Tread1 => &art.moving[0],
            ExcavatorPose::Tread2 => &art.moving[1],
            ExcavatorPose::Work1 => &art.action[0],
            ExcavatorPose::Work2 => &art.action[1],
            ExcavatorPose::Work3 => &art.action[2],
            ExcavatorPose::Work4 => &art.action[3],
        }
    }

    /// A complete Excavator chassis pose beneath its independent cargo meter.
    pub fn excavator_frame(&self, faction: Faction, pose: ExcavatorPose) -> Rect {
        self.excavator_frame_row(pose)[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::excavator_frame`].
    pub fn excavator_frame_accent(&self, pose: ExcavatorPose) -> Rect {
        self.excavator_frame_row(pose)[ACCENT]
    }

    /// The recessed Excavator meter at one of five load-fraction levels.
    pub fn excavator_cargo(&self, cargo: usize) -> Rect {
        self.excavator_cargo[cargo.min(EXCAVATOR_CARGO_LEVELS - 1)]
    }

    fn moving_unit_row(&self, kind: UnitKind, frame: usize) -> &[Rect; 3] {
        let art = &self.units[kind as usize];
        frame
            .checked_sub(1)
            .and_then(|index| art.moving.get(index))
            .unwrap_or(&art.base)
    }

    /// A unit's authored locomotion phase. Frame 0 is the ordinary base art;
    /// frames 1 and 2 select the two movement poses.
    pub fn unit_moving(&self, kind: UnitKind, faction: Faction, frame: usize) -> Rect {
        self.moving_unit_row(kind, frame)[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::unit_moving`].
    pub fn unit_moving_accent(&self, kind: UnitKind, frame: usize) -> Rect {
        self.moving_unit_row(kind, frame)[ACCENT]
    }

    /// The construction lattice: dense early, sparse near completion.
    pub fn scaffold(&self, dense: bool) -> Rect {
        self.scaffold[usize::from(!dense)]
    }

    /// A death-scatter hull shard.
    pub fn debris(&self, variant: usize) -> Rect {
        self.debris[variant % 3]
    }

    fn unit_row(&self, kind: UnitKind) -> &[Rect; 3] {
        &self.units[kind as usize].base
    }

    fn unit_action_row(&self, kind: UnitKind, frame: usize) -> Option<&[Rect; 3]> {
        self.units[kind as usize].action.get(frame)
    }

    /// A unit's zero-based authored action frame. Harvester and invalid frame
    /// requests fall back to the ordinary ready sprite.
    pub fn unit_action(&self, kind: UnitKind, faction: Faction, frame: usize) -> Rect {
        self.unit_action_row(kind, frame)
            .unwrap_or_else(|| self.unit_row(kind))[faction_index(faction)]
    }

    /// The allegiance mask matched to [`Self::unit_action`].
    pub fn unit_action_accent(&self, kind: UnitKind, frame: usize) -> Rect {
        self.unit_action_row(kind, frame)
            .unwrap_or_else(|| self.unit_row(kind))[ACCENT]
    }

    /// The unit sprite region for a kind and faction.
    pub fn unit(&self, kind: UnitKind, faction: Faction) -> Rect {
        self.unit_row(kind)[faction_index(faction)]
    }

    pub(crate) fn unit_rig(&self, kind: UnitKind) -> Option<&UnitRig> {
        self.unit_rigs.get(&kind)
    }

    pub(crate) fn scout_radar(&self) -> Option<Rect> {
        self.scout_radar
    }

    pub(crate) fn array_rig(&self) -> Option<&ArrayRig> {
        self.array_rig.as_ref()
    }

    /// The spade row for a Bombard's deployment, from stowed (row 0) to
    /// fully braced (row 4).
    pub(crate) fn bombard_spades(&self, brace_ticks: u8) -> Option<Rect> {
        let deploy = UnitKind::Bombard
            .stats()
            .brace
            .map_or(1, |brace| u16::from(brace.deploy_ticks.max(1)));
        let row = (u16::from(brace_ticks) * 4).div_ceil(deploy).min(4);
        self.bombard_spades.map(|rows| rows[usize::from(row)])
    }

    /// The allegiance-accent mask over a unit's faction-colored
    /// regions: grayscale in the atlas, tinted at draw time.
    pub fn unit_accent(&self, kind: UnitKind) -> Rect {
        self.unit_row(kind)[ACCENT]
    }
}

/// Every clip the shell plays. Generated by `tools/gen_sounds.py`.
pub struct Sounds {
    /// One clip per sound kind, named by [`crate::mixer::spec`]. The rocket
    /// motor plays from `rocket_motors` instead.
    effects: std::collections::HashMap<SoundKind, Sound>,
    /// The zap's lower sibling, alternated per shot.
    pub laser2: Sound,
    /// Independently loaded buffers, because the backend stops by sound id.
    pub rocket_motors: Vec<Sound>,
    /// Front-end industrial ambience.
    pub music_menu: Sound,
    /// The calm match bed.
    pub music_calm: Sound,
    /// Rhythmic pressure layered over the calm bed during combat.
    pub music_combat: Sound,
    /// A neutral result bed for draws.
    pub music_result: Sound,
    /// The local-player victory bed.
    pub music_victory: Sound,
    /// The local-player defeat or surrender bed.
    pub music_defeat: Sound,
}

async fn clip(name: &str) -> Result<Sound> {
    let candidate = std::env::var("OXIDE_SOUND_BANK")
        .ok()
        .map(|root| std::path::PathBuf::from(root).join(format!("{name}.wav")))
        .filter(|path| path.is_file());
    let path =
        candidate.unwrap_or_else(|| resource_root().join(format!("assets/sounds/{name}.wav")));
    let bytes = read_resource(&path).context("loading a sound (run from the workspace root)")?;
    load_sound_from_bytes(&bytes)
        .await
        .with_context(|| format!("decoding {}", path.display()))
}

impl Sounds {
    /// Loads every clip up front, like [`Sprites::load`].
    pub async fn load() -> Result<Self> {
        let mut rocket_motors = Vec::with_capacity(crate::rocket_audio::MOTOR_VOICES);
        for _ in 0..crate::rocket_audio::MOTOR_VOICES {
            rocket_motors.push(clip("avalanche_motor").await?);
        }
        let mut effects = std::collections::HashMap::new();
        for kind in SoundKind::ALL {
            if kind != SoundKind::RocketMotor {
                effects.insert(kind, clip(crate::mixer::spec(kind).clip).await?);
            }
        }
        Ok(Self {
            effects,
            laser2: clip("laser2").await?,
            rocket_motors,
            music_menu: clip("music_menu").await?,
            music_calm: clip("music_calm").await?,
            music_combat: clip("music_combat").await?,
            music_result: clip("music_result").await?,
            music_victory: clip("music_victory").await?,
            music_defeat: clip("music_defeat").await?,
        })
    }

    /// The clip a sound kind plays.
    pub fn effect(&self, kind: SoundKind) -> &Sound {
        match kind {
            SoundKind::RocketMotor => &self.rocket_motors[0],
            _ => &self.effects[&kind],
        }
    }
}

/// The asset manifest, checked without a GPU.
///
/// [`Sprites::load`] fails on a missing region, including any row a unit
/// or building kind needs, but it needs a window, which CI never opens.
/// These tests read `atlas.json` as plain data instead, so a regenerated
/// atlas that dropped a row, or a kind whose art was never generated,
/// fails by name in the ordinary test run.
#[cfg(test)]
mod tests;
